const {onRequest}=require('firebase-functions/v2/https');
const {defineSecret}=require('firebase-functions/params');
const admin=require('firebase-admin');
const crypto=require('crypto');
admin.initializeApp();const db=admin.firestore();
const PAYU_KEY=defineSecret('PAYU_KEY');const PAYU_SALT=defineSecret('PAYU_SALT');
const sha=s=>crypto.createHash('sha512').update(s).digest('hex').toLowerCase();
const cors=(res)=>{res.set('Access-Control-Allow-Origin','*');res.set('Access-Control-Allow-Headers','Content-Type, Authorization');res.set('Access-Control-Allow-Methods','POST,OPTIONS')};
async function authUser(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw new Error('AUTH');return admin.auth().verifyIdToken(h.slice(7))}
exports.initPayuPayment=onRequest({secrets:[PAYU_KEY,PAYU_SALT]},async(req,res)=>{cors(res);if(req.method==='OPTIONS')return res.status(204).send('');if(req.method!=='POST')return res.status(405).json({message:'POST required'});try{const u=await authUser(req);const {applicationDocId}=req.body||{};const a=await db.collection('applications').doc(applicationDocId).get();if(!a.exists||a.data().userId!==u.uid)return res.status(403).json({message:'Invalid application'});const d=a.data();if(d.paymentStatus==='Paid')return res.status(409).json({message:'Already paid'});const action=await db.collection('serviceActions').doc(d.actionId).get();if(!action.exists)return res.status(400).json({message:'Action not found'});const ad=action.data(),amount=Number(ad.serviceCharge||0).toFixed(2);if(Number(amount)!==Number(d.amount))return res.status(400).json({message:'Amount mismatch'});if((ad.availabilityStatus||((ad.available!==false)?'Available':'Unavailable'))!=='Available')return res.status(400).json({message:'Service action unavailable'});const settings=await db.collection('settings').doc('payu').get();const ps=settings.exists?settings.data():{};const key=PAYU_KEY.value();const salt=PAYU_SALT.value();const txnid='KCSC'+Date.now()+Math.random().toString(36).slice(2,7).toUpperCase();const firstname=String(d.userName||'Customer').trim().split(/\s+/)[0]||'Customer';const email=d.email||`${d.mobile}@customer.invalid`;const productinfo=`KCSC ${d.serviceName||'Digital Service'} - ${d.actionName||'Application'}`.slice(0,90);const udf1=d.applicationId||'';const hashString=`${key}|${txnid}|${amount}|${productinfo}|${firstname}|${email}|${udf1}||||||||||${salt}`;const hash=sha(hashString);const actionUrl=(ps.environment==='production')?'https://secure.payu.in/_payment':'https://test.payu.in/_payment';const successUrl=ps.successUrl||'';const failureUrl=ps.failureUrl||successUrl;if(!successUrl||!failureUrl)return res.status(400).json({message:'PayU success/failure URLs missing in Admin settings'});await db.collection('payments').doc(txnid).set({paymentId:txnid,applicationDocId,applicationId:d.applicationId,userId:u.uid,amount:Number(amount),status:'Pending',createdAt:admin.firestore.FieldValue.serverTimestamp()});await a.ref.update({paymentTransactionId:txnid,updatedAt:admin.firestore.FieldValue.serverTimestamp()});return res.json({action:actionUrl,fields:{key,txnid,amount,productinfo,firstname,email,phone:d.mobile||'',surl:successUrl,furl:failureUrl,udf1,hash}})}catch(e){console.error(e);return res.status(e.message==='AUTH'?401:500).json({message:e.message==='AUTH'?'Login required':'Payment init failed'})}});
exports.payuCallback=onRequest({secrets:[PAYU_KEY,PAYU_SALT]},async(req,res)=>{try{const p=req.body||{},salt=PAYU_SALT.value(),key=PAYU_KEY.value();const reverse=p.additionalCharges?`${p.additionalCharges}|${salt}|${p.status}||||||${p.udf5||''}|${p.udf4||''}|${p.udf3||''}|${p.udf2||''}|${p.udf1||''}|${p.email||''}|${p.firstname||''}|${p.productinfo||''}|${p.amount||''}|${p.txnid||''}|${key}`:`${salt}|${p.status}||||||${p.udf5||''}|${p.udf4||''}|${p.udf3||''}|${p.udf2||''}|${p.udf1||''}|${p.email||''}|${p.firstname||''}|${p.productinfo||''}|${p.amount||''}|${p.txnid||''}|${key}`;if(sha(reverse)!==String(p.hash||'').toLowerCase())return res.status(400).send('Invalid hash');const pay=await db.collection('payments').doc(p.txnid).get();if(!pay.exists)return res.status(404).send('Unknown transaction');const pd=pay.data();const success=String(p.status||'').toLowerCase()==='success';await pay.ref.update({status:success?'Paid':'Failed',mihpayid:p.mihpayid||'',bankRef:p.bank_ref_num||'',updatedAt:admin.firestore.FieldValue.serverTimestamp()});const ar=db.collection('applications').doc(pd.applicationDocId);const app=await ar.get();if(app.exists){await ar.update({paymentStatus:success?'Paid':'Failed',status:success?'Pending':'Payment Failed',transactionReference:p.txnid,mihpayid:p.mihpayid||'',updatedAt:admin.firestore.FieldValue.serverTimestamp()});const d=app.data();await db.collection('publicApplicationStatus').doc(d.applicationId).set({applicationId:d.applicationId,mobileLast4:String(d.mobile||'').slice(-4),serviceName:d.serviceName||'',actionName:d.actionName||'',paymentStatus:success?'Paid':'Failed',status:success?'Pending':'Payment Failed',updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true})}const settings=await db.collection('settings').doc('payu').get();const url=(settings.data()?.portalReturnUrl)||'/portal/my-applications.html';res.redirect(302,url+'?payment='+(success?'success':'failed'))}catch(e){console.error(e);res.status(500).send('Callback error')}});
