const {onRequest}=require('firebase-functions/v2/https');
const {defineSecret}=require('firebase-functions/params');
const admin=require('firebase-admin');
const crypto=require('crypto');
admin.initializeApp();
const db=admin.firestore();
const PAYU_KEY=defineSecret('PAYU_KEY');
const PAYU_SALT=defineSecret('PAYU_SALT');
const sha=s=>crypto.createHash('sha512').update(String(s)).digest('hex').toLowerCase();
const cors=(res)=>{res.set('Access-Control-Allow-Origin','*');res.set('Access-Control-Allow-Headers','Content-Type, Authorization');res.set('Access-Control-Allow-Methods','POST,OPTIONS')};
async function authUser(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw new Error('AUTH');return admin.auth().verifyIdToken(h.slice(7))}
async function payuSettings(){const s=await db.collection('settings').doc('payu').get();return s.exists?s.data():{}}
function endpoints(env){return env==='production'?{pay:'https://secure.payu.in/_payment',verify:'https://info.payu.in/merchant/postservice.php?form=2'}:{pay:'https://test.payu.in/_payment',verify:'https://test.payu.in/merchant/postservice.php?form=2'}}
async function verifyPayment(txnid,env,key,salt){const command='verify_payment',hash=sha(`${key}|${command}|${txnid}|${salt}`),body=new URLSearchParams({key,command,var1:txnid,hash});const r=await fetch(endpoints(env).verify,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const text=await r.text();let json={};try{json=JSON.parse(text)}catch(_){throw new Error('PayU verify invalid response')}if(!r.ok)throw new Error('PayU verify failed');const detail=json.transaction_details?.[txnid]||json.result?.[txnid]||null;return {raw:json,detail}}
function reverseHash(p,key,salt){return p.additionalCharges?`${p.additionalCharges}|${salt}|${p.status}||||||${p.udf5||''}|${p.udf4||''}|${p.udf3||''}|${p.udf2||''}|${p.udf1||''}|${p.email||''}|${p.firstname||''}|${p.productinfo||''}|${p.amount||''}|${p.txnid||''}|${key}`:`${salt}|${p.status}||||||${p.udf5||''}|${p.udf4||''}|${p.udf3||''}|${p.udf2||''}|${p.udf1||''}|${p.email||''}|${p.firstname||''}|${p.productinfo||''}|${p.amount||''}|${p.txnid||''}|${key}`}
async function finalize(txnid,p,source='callback'){
 const payRef=db.collection('payments').doc(txnid),pay=await payRef.get();if(!pay.exists)throw new Error('Unknown transaction');const pd=pay.data(),settings=await payuSettings(),key=PAYU_KEY.value(),salt=PAYU_SALT.value();
 const verified=await verifyPayment(txnid,settings.environment||'test',key,salt);const d=verified.detail||{};const verifiedStatus=String(d.status||d.unmappedstatus||p.status||'').toLowerCase();const success=['success','captured'].includes(verifiedStatus);const amountOk=Math.abs(Number(d.amt||d.amount||p.amount||0)-Number(pd.amount||0))<0.01;const successFinal=success&&amountOk;
 await payRef.set({status:successFinal?'Paid':(success?'Amount Mismatch':'Failed'),mihpayid:d.mihpayid||p.mihpayid||'',bankRef:d.bank_ref_num||p.bank_ref_num||'',verifiedStatus,verifiedAmount:Number(d.amt||d.amount||p.amount||0),verificationSource:source,verifiedAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});
 const ar=db.collection('applications').doc(pd.applicationDocId),app=await ar.get();if(app.exists){const ad=app.data(),appStatus=successFinal?'Pending':(success?'Payment Review':'Payment Failed');await ar.update({paymentStatus:successFinal?'Paid':(success?'Review':'Failed'),status:appStatus,transactionReference:txnid,mihpayid:d.mihpayid||p.mihpayid||'',updatedAt:admin.firestore.FieldValue.serverTimestamp()});await db.collection('publicApplicationStatus').doc(ad.applicationId).set({applicationId:ad.applicationId,mobileLast4:String(ad.mobile||'').slice(-4),serviceName:ad.serviceName||'',actionName:ad.actionName||'',paymentStatus:successFinal?'Paid':(success?'Review':'Failed'),status:appStatus,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true})}
 return successFinal;
}
exports.initPayuPayment=onRequest({secrets:[PAYU_KEY,PAYU_SALT]},async(req,res)=>{cors(res);if(req.method==='OPTIONS')return res.status(204).send('');if(req.method!=='POST')return res.status(405).json({message:'POST required'});try{const u=await authUser(req);const {applicationDocId}=req.body||{};const a=await db.collection('applications').doc(applicationDocId).get();if(!a.exists||a.data().userId!==u.uid)return res.status(403).json({message:'Invalid application'});const d=a.data();if(d.paymentStatus==='Paid')return res.status(409).json({message:'Already paid'});const action=await db.collection('serviceActions').doc(d.actionId).get();if(!action.exists)return res.status(400).json({message:'Action not found'});const ad=action.data(),amount=Number(ad.serviceCharge||0).toFixed(2);if(Number(amount)!==Number(d.amount))return res.status(400).json({message:'Amount mismatch'});if((ad.availabilityStatus||((ad.available!==false)?'Available':'Unavailable'))!=='Available')return res.status(400).json({message:'Service action unavailable'});const ps=await payuSettings(),key=PAYU_KEY.value(),salt=PAYU_SALT.value(),txnid='KCSC'+Date.now()+Math.random().toString(36).slice(2,7).toUpperCase(),firstname=String(d.userName||'Customer').trim().split(/\s+/)[0]||'Customer',email=d.email||`${d.mobile}@customer.invalid`,productinfo=`KCSC ${d.serviceName||'Digital Service'} - ${d.actionName||'Application'}`.slice(0,90),udf1=d.applicationId||'',hash=sha(`${key}|${txnid}|${amount}|${productinfo}|${firstname}|${email}|${udf1}||||||||||${salt}`),successUrl=ps.successUrl||'',failureUrl=ps.failureUrl||successUrl;if(!successUrl||!failureUrl)return res.status(400).json({message:'PayU success/failure URLs missing in Admin settings'});await db.collection('payments').doc(txnid).set({paymentId:txnid,applicationDocId,applicationId:d.applicationId,userId:u.uid,amount:Number(amount),status:'Pending',createdAt:admin.firestore.FieldValue.serverTimestamp()});await a.ref.update({paymentTransactionId:txnid,updatedAt:admin.firestore.FieldValue.serverTimestamp()});return res.json({action:endpoints(ps.environment||'test').pay,fields:{key,txnid,amount,productinfo,firstname,email,phone:d.mobile||'',surl:successUrl,furl:failureUrl,udf1,hash}})}catch(e){console.error(e);return res.status(e.message==='AUTH'?401:500).json({message:e.message==='AUTH'?'Login required':'Payment init failed: '+e.message})}});
exports.payuCallback=onRequest({secrets:[PAYU_KEY,PAYU_SALT]},async(req,res)=>{try{const p=req.body||{},key=PAYU_KEY.value(),salt=PAYU_SALT.value();if(sha(reverseHash(p,key,salt))!==String(p.hash||'').toLowerCase())return res.status(400).send('Invalid hash');const success=await finalize(p.txnid,p,'browser-callback');const settings=await payuSettings(),url=settings.portalReturnUrl||'/portal/my-applications.html';return res.redirect(302,url+(url.includes('?')?'&':'?')+'payment='+(success?'success':'failed'))}catch(e){console.error(e);return res.status(500).send('Callback error')}});
exports.payuWebhook=onRequest({secrets:[PAYU_KEY,PAYU_SALT]},async(req,res)=>{try{const p=req.body||{},key=PAYU_KEY.value(),salt=PAYU_SALT.value();if(!p.txnid)return res.status(400).send('Missing txnid');if(p.hash&&sha(reverseHash(p,key,salt))!==String(p.hash||'').toLowerCase())return res.status(400).send('Invalid hash');await finalize(p.txnid,p,'webhook');return res.status(200).send('OK')}catch(e){console.error(e);return res.status(500).send('Webhook error')}});
exports.reconcilePayuPayment=onRequest({secrets:[PAYU_KEY,PAYU_SALT]},async(req,res)=>{cors(res);if(req.method==='OPTIONS')return res.status(204).send('');try{const u=await authUser(req);if(String(u.email||'').toLowerCase()!=='niteshkhobragade8@gmail.com')return res.status(403).json({message:'Admin only'});const {txnid}=req.body||{};if(!txnid)return res.status(400).json({message:'txnid required'});const success=await finalize(txnid,{txnid},'admin-reconcile');return res.json({ok:true,paid:success})}catch(e){console.error(e);return res.status(500).json({message:e.message})}});
