import { db } from './firebase-config.js';
import { doc, onSnapshot, setDoc, collection, addDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const FIXED=[
 ['dashboard','Dashboard','fa-solid fa-house',10],
 ['applications','Applications','fa-solid fa-file-circle-check',20],
 ['users','Users / Customers','fa-solid fa-users',30],
 ['payments','Payments / PayU','fa-solid fa-indian-rupee-sign',40],
 ['portalbuilder','Services / Actions / Forms','fa-solid fa-list-check',60],
 ['servicecharges','Service Charges','fa-solid fa-tags',65],
 ['userportalcms','Website CMS','fa-solid fa-window-maximize',70],
 ['youtube','YouTube','fa-brands fa-youtube',80],
 ['notifications','Notifications','fa-solid fa-bell',90],
 ['analytics','Analytics','fa-solid fa-chart-line',100],
 ['admineditor','Admin Dashboard CMS','fa-solid fa-sliders',110],
 ['themes','Theme Manager','fa-solid fa-palette',120],
 ['recyclebin','Recycle Bin','fa-solid fa-recycle',130],
 ['settings','Portal Settings','fa-solid fa-gear',140]
];
const DEF_THEME={name:'Original Admin',green:'#00c853',yellow:'#ffd600',pink:'#ff4081',red:'#ff1744',blue:'#2979ff',text:'#111827',bg:'#f4f7fc',panel:'#ffffff',line:'#e5e7eb',side1:'#00c853',side2:'#ff1744',menuText:'#ffffff',radius:18,sidebarWidth:260};
let state={menu:{},pageOverrides:{},theme:{...DEF_THEME},themes:[],customPages:[],customMenus:[]},editCustom=null,editTheme=null,editMenu=null;
function message(t,type='info'){if($('aeMessage')){$('aeMessage').textContent=t;$('aeMessage').className='settings-message '+type}}
function menuCfg(key){const d=FIXED.find(x=>x[0]===key);return {...{label:d?.[1]||key,icon:d?.[2]||'fa-solid fa-file',order:d?.[3]||999,visible:true},...(state.menu?.[key]||{})}}
function fixedPageCfg(key){const d=FIXED.find(x=>x[0]===key), m=menuCfg(key), o=state.pageOverrides?.[key]||{};return {key,name:o.name||m.label||d?.[1]||key,heading:o.heading||'',order:Number(o.order??m.order??999),visible:o.visible!==false&&m.visible!==false,deleted:o.deleted===true}}
function applyTheme(t=DEF_THEME){const r=document.documentElement;r.style.setProperty('--green',t.green||DEF_THEME.green);r.style.setProperty('--yellow',t.yellow||DEF_THEME.yellow);r.style.setProperty('--pink',t.pink||DEF_THEME.pink);r.style.setProperty('--red',t.red||DEF_THEME.red);r.style.setProperty('--blue',t.blue||DEF_THEME.blue);r.style.setProperty('--black',t.text||DEF_THEME.text);r.style.setProperty('--bg',t.bg||DEF_THEME.bg);r.style.setProperty('--panel',t.panel||DEF_THEME.panel);r.style.setProperty('--line',t.line||DEF_THEME.line);r.style.setProperty('--radius',(Number(t.radius)||18)+'px');r.style.setProperty('--sidebar',(Number(t.sidebarWidth)||260)+'px');r.style.setProperty('--admin-page-bg',t.bg||DEF_THEME.bg);r.style.setProperty('--admin-side-1',t.side1||DEF_THEME.side1);r.style.setProperty('--admin-side-2',t.side2||DEF_THEME.side2);r.style.setProperty('--admin-menu-text',t.menuText||'#fff');document.body.classList.add('admin-editor-themed')}
function ensureCustomPage(x){const key='custom_'+x.id;let sec=$(key+'Page');if(!sec){sec=document.createElement('section');sec.id=key+'Page';sec.className='page admin-custom-page';document.querySelector('.main-content')?.appendChild(sec)}sec.innerHTML=`<div class="page-intro"><div><h2>${esc(x.heading||x.name||'Admin Page')}</h2><p>Custom Admin Page</p></div></div><div class="dashboard-info-box"><div class="ae-custom-content">${esc(x.content||'')}</div></div>`}
function ensureCustomMenu(x){let li=document.querySelector(`#sidebarMenu li[data-ae-menu="${CSS.escape(x.id)}"]`);if(!li){li=document.createElement('li');li.dataset.aeMenu=x.id;li.innerHTML='<i></i><span></span>';$('sidebarMenu')?.insertBefore(li,$('logoutBtn'))}li.dataset.page=x.target||'dashboard';li.style.display=x.visible===false?'none':'';li.dataset.aeOrder=String(Number(x.order)||900);li.querySelector('i').className=x.icon||'fa-solid fa-link';li.querySelector('span').textContent=x.name||'Menu'}
function applyPages(){FIXED.forEach(([key])=>{const c=fixedPageCfg(key),sec=$(key+'Page');if(sec){sec.dataset.aeDeleted=String(c.deleted);const h=sec.querySelector('.page-intro h2');if(h&&c.heading)h.textContent=c.heading}});state.customPages.forEach(ensureCustomPage)}
function applyMenu(){const ul=$('sidebarMenu');if(!ul)return;FIXED.forEach(([key])=>{const li=ul.querySelector(`li[data-page="${key}"]:not([data-ae-menu])`);if(!li)return;const c=menuCfg(key),p=fixedPageCfg(key);li.style.display=(c.visible===false||p.deleted)?'none':'';li.dataset.aeOrder=String(Number(c.order)||999);li.querySelector('span').textContent=c.label;li.querySelector('i').className=c.icon});ul.querySelectorAll('li[data-ae-menu]').forEach(x=>x.remove());state.customPages.filter(x=>x.visible!==false).forEach(x=>ensureCustomMenu({id:'page_'+x.id,name:x.name,icon:x.icon,target:'custom_'+x.id,order:x.order,visible:x.visible}));state.customMenus.forEach(ensureCustomMenu);[...ul.querySelectorAll('li[data-page]')].sort((a,b)=>Number(a.dataset.aeOrder||999)-Number(b.dataset.aeOrder||999)).forEach(li=>ul.insertBefore(li,$('logoutBtn')))}
function pageTargets(){return [...FIXED.filter(([k])=>!fixedPageCfg(k).deleted).map(([k,n])=>({value:k,label:n})),...state.customPages.map(x=>({value:'custom_'+x.id,label:x.name||'Admin Page'}))]}
function renderTargetSelect(){const s=$('aeNewMenuTarget');if(!s)return;s.innerHTML=pageTargets().map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('')}
function renderMenu(){const b=$('aeMenuList');if(!b)return;const fixed=FIXED.map(([key])=>{const c=menuCfg(key),p=fixedPageCfg(key);return `<div class="ae-menu-row" data-key="${key}" data-kind="fixed"><div class="ae-icon-preview"><i class="${esc(c.icon)}"></i></div><input class="ae-label" value="${esc(c.label)}"><input class="ae-icon-input" value="${esc(c.icon)}"><input class="ae-order" type="number" value="${Number(c.order)}"><select class="ae-visible"><option value="true" ${c.visible!==false&&!p.deleted?'selected':''}>Show</option><option value="false" ${c.visible===false||p.deleted?'selected':''}>Hide</option></select><button class="action-btn delete ae-delete-menu" type="button">🗑</button></div>`}).join('');const custom=state.customMenus.map((x,i)=>`<div class="ae-menu-row ae-menu-row-custom" data-index="${i}" data-kind="custom"><div class="ae-icon-preview"><i class="${esc(x.icon||'fa-solid fa-link')}"></i></div><input class="ae-label" value="${esc(x.name||'Menu')}"><input class="ae-icon-input" value="${esc(x.icon||'fa-solid fa-link')}"><input class="ae-order" type="number" value="${Number(x.order||180)}"><select class="ae-visible"><option value="true" ${x.visible!==false?'selected':''}>Show</option><option value="false" ${x.visible===false?'selected':''}>Hide</option></select><button class="action-btn delete ae-delete-menu" type="button">🗑</button><select class="ae-target">${pageTargets().map(p=>`<option value="${esc(p.value)}" ${p.value===x.target?'selected':''}>${esc(p.label)}</option>`).join('')}</select></div>`).join('');b.innerHTML=fixed+custom}
function collectMenu(){const out={};document.querySelectorAll('.ae-menu-row[data-kind="fixed"]').forEach(r=>{out[r.dataset.key]={label:r.querySelector('.ae-label').value.trim()||r.dataset.key,icon:r.querySelector('.ae-icon-input').value.trim()||'fa-solid fa-file',order:Number(r.querySelector('.ae-order').value||999),visible:r.querySelector('.ae-visible').value!=='false'}});document.querySelectorAll('.ae-menu-row[data-kind="custom"]').forEach(r=>{const i=Number(r.dataset.index);if(!state.customMenus[i])return;state.customMenus[i]={...state.customMenus[i],name:r.querySelector('.ae-label').value.trim()||'Menu',icon:r.querySelector('.ae-icon-input').value.trim()||'fa-solid fa-link',order:Number(r.querySelector('.ae-order').value||180),visible:r.querySelector('.ae-visible').value!=='false',target:r.querySelector('.ae-target')?.value||state.customMenus[i].target}});return out}
function themeFromForm(){return {name:$('aeThemeName').value.trim()||'Admin Theme',green:$('aeGreen').value,yellow:$('aeYellow').value,pink:$('aePink').value,red:$('aeRed').value,blue:$('aeBlue').value,text:$('aeText').value,bg:$('aeBg').value,panel:$('aePanel').value,line:$('aeLine').value,side1:$('aeSide1').value,side2:$('aeSide2').value,menuText:$('aeMenuText').value,radius:Number($('aeRadius').value||18),sidebarWidth:Number($('aeSidebarWidth').value||260)}}
function fillTheme(t=DEF_THEME){for(const [id,k] of Object.entries({aeThemeName:'name',aeGreen:'green',aeYellow:'yellow',aePink:'pink',aeRed:'red',aeBlue:'blue',aeText:'text',aeBg:'bg',aePanel:'panel',aeLine:'line',aeSide1:'side1',aeSide2:'side2',aeMenuText:'menuText',aeRadius:'radius',aeSidebarWidth:'sidebarWidth'}))if($(id))$(id).value=t[k]??DEF_THEME[k]}
function renderThemes(){const b=$('aeThemeList');if(!b)return;b.innerHTML=state.themes.length?state.themes.map((t,i)=>`<article class="content-card"><h3>${esc(t.name||'Admin Theme')}</h3><div class="ae-theme-swatch" style="--ae1:${esc(t.green)};--ae2:${esc(t.blue)};--ae3:${esc(t.pink)};--ae4:${esc(t.red)}"></div><div class="card-actions"><button class="action-btn edit" data-te="${i}">✏ Edit</button><button class="action-btn copy" data-ta="${i}">✓ Apply</button><button class="action-btn delete" data-td="${i}">🗑 Delete</button></div></article>`).join(''):'<div class="empty-state">No saved Admin themes.</div>'}
function clearPage(){editCustom=null;for(const id of ['aePageName','aePageHeading','aePageContent'])if($(id))$(id).value='';if($('aePageIcon'))$('aePageIcon').value='fa-solid fa-file';if($('aePageOrder'))$('aePageOrder').value='180';if($('aePageVisible'))$('aePageVisible').value='true';if($('aeSavePage'))$('aeSavePage').textContent='Save Admin Page'}
function renderPages(){const b=$('aePagesList');if(!b)return;const fixed=FIXED.map(([key,n,icon])=>{const p=fixedPageCfg(key);return `<article class="content-card ${p.deleted?'ae-deleted-card':''}"><span class="status-badge ${p.visible&&!p.deleted?'published':'draft'}">${p.deleted?'Deleted':p.visible?'Visible':'Hidden'}</span><h3><i class="${esc(icon)}"></i> ${esc(p.name)}</h3><p>${esc(p.heading||'Existing core Admin page')}</p><small>Order ${p.order}</small><div class="card-actions"><button class="action-btn edit" data-fe="${key}">✏ Edit</button><button class="action-btn delete" data-fd="${key}" ${key==='admineditor'?'disabled title="Admin Dashboard CMS protected"':''}>🗑 Delete</button></div></article>`}).join('');const custom=state.customPages.map((x,i)=>`<article class="content-card"><span class="status-badge ${x.visible===false?'draft':'published'}">${x.visible===false?'Hidden':'Visible'}</span><h3><i class="${esc(x.icon||'fa-solid fa-file')}"></i> ${esc(x.name||'Admin Page')}</h3><p>${esc(x.heading||'')}</p><small>Order ${Number(x.order||180)}</small><div class="card-actions"><button class="action-btn edit" data-ce="${i}">✏ Edit</button><button class="action-btn delete" data-cd="${i}">🗑 Delete</button></div></article>`).join('');b.innerHTML=fixed+custom}
async function persist(){await setDoc(doc(db,'settings','adminEditor'),{...state,updatedAt:serverTimestamp()},{merge:false})}
async function trash(type,sourceId,data){await addDoc(collection(db,'recycleBin'),{type,sourceId,data,deletedAt:serverTimestamp()})}
function refreshAll(){applyPages();applyMenu();renderTargetSelect();renderMenu();renderPages();renderThemes()}
$('aeSaveMenu')?.addEventListener('click',async()=>{state.menu=collectMenu();await persist();refreshAll();message('Admin menu saved & applied.','success')});
$('aeResetMenu')?.addEventListener('click',async()=>{if(!confirm('Original fixed Admin menu restore karein?'))return;state.menu={};await persist();refreshAll();message('Original menu restored.','success')});
$('aeAddMenu')?.addEventListener('click',async()=>{const name=$('aeNewMenuName').value.trim();if(!name)return alert('Menu Name required.');state.customMenus.push({id:'m'+Date.now(),name,icon:$('aeNewMenuIcon').value.trim()||'fa-solid fa-link',target:$('aeNewMenuTarget').value||'dashboard',order:Number($('aeNewMenuOrder').value||180),visible:$('aeNewMenuVisible').value!=='false'});await persist();$('aeNewMenuName').value='';refreshAll();message('New Admin menu added.','success')});
$('aeClearMenu')?.addEventListener('click',()=>{$('aeNewMenuName').value='';$('aeNewMenuIcon').value='fa-solid fa-link';$('aeNewMenuOrder').value='180'});
$('aeMenuList')?.addEventListener('click',async e=>{const b=e.target.closest('.ae-delete-menu');if(!b)return;const r=b.closest('.ae-menu-row');if(r.dataset.kind==='fixed'){const key=r.dataset.key;if(key==='admineditor')return alert('Admin Dashboard CMS menu protected hai.');const old=menuCfg(key);if(!confirm(`${old.label} menu Recycle Bin me bheje?`))return;await trash('adminMenu',key,{kind:'fixed',key,config:old});state.menu[key]={...old,visible:false};}else{const i=Number(r.dataset.index),old=state.customMenus[i];if(!old)return;if(!confirm(`${old.name} menu Recycle Bin me bheje?`))return;await trash('adminMenu',old.id,{kind:'custom',menu:old});state.customMenus.splice(i,1)}await persist();refreshAll();message('Menu moved to Recycle Bin.','success')});
$('aePreviewTheme')?.addEventListener('click',()=>applyTheme(themeFromForm()));
$('aeSaveTheme')?.addEventListener('click',async()=>{const t=themeFromForm();if(editTheme!==null)state.themes[editTheme]=t;else state.themes.push(t);state.theme=t;editTheme=null;await persist();applyTheme(t);renderThemes();message('Admin theme saved & applied.','success')});
$('aeResetTheme')?.addEventListener('click',async()=>{fillTheme(DEF_THEME);state.theme={...DEF_THEME};await persist();applyTheme(DEF_THEME);message('Original Admin theme restored.','success')});
$('aeThemeList')?.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.te!==undefined){editTheme=Number(b.dataset.te);fillTheme(state.themes[editTheme])}else if(b.dataset.ta!==undefined){state.theme={...state.themes[Number(b.dataset.ta)]};await persist();fillTheme(state.theme);applyTheme(state.theme);message('Theme applied.','success')}else if(b.dataset.td!==undefined){const i=Number(b.dataset.td),old=state.themes[i];if(!confirm('Saved Admin theme Recycle Bin me bheje?'))return;await trash('adminTheme','t'+Date.now(),{theme:old});state.themes.splice(i,1);await persist();renderThemes();message('Theme moved to Recycle Bin.','success')}});
$('aeSavePage')?.addEventListener('click',async()=>{const name=$('aePageName').value.trim();if(!name)return alert('Page Name required.');const x={id:editCustom!==null?state.customPages[editCustom].id:'p'+Date.now(),name,icon:$('aePageIcon').value.trim()||'fa-solid fa-file',heading:$('aePageHeading').value.trim()||name,content:$('aePageContent').value.trim(),order:Number($('aePageOrder').value||180),visible:$('aePageVisible').value!=='false'};if(editCustom!==null)state.customPages[editCustom]=x;else state.customPages.push(x);await persist();clearPage();refreshAll();message('Admin page saved / updated.','success')});
$('aeClearPage')?.addEventListener('click',clearPage);
$('aePagesList')?.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.ce!==undefined){editCustom=Number(b.dataset.ce);const x=state.customPages[editCustom];$('aePageName').value=x.name||'';$('aePageIcon').value=x.icon||'';$('aePageHeading').value=x.heading||'';$('aePageContent').value=x.content||'';$('aePageOrder').value=x.order??180;$('aePageVisible').value=String(x.visible!==false);$('aeSavePage').textContent='Update Admin Page'}else if(b.dataset.cd!==undefined){const i=Number(b.dataset.cd),old=state.customPages[i];if(!confirm('Custom Admin page Recycle Bin me bheje?'))return;await trash('adminPage',old.id,{kind:'custom',page:old});state.customPages.splice(i,1);document.querySelector(`#sidebarMenu li[data-page="custom_${old.id}"]`)?.remove();$('custom_'+old.id+'Page')?.remove();await persist();refreshAll();message('Admin page moved to Recycle Bin.','success')}else if(b.dataset.fe!==undefined){const key=b.dataset.fe,p=fixedPageCfg(key);const name=prompt('Page / Menu Name',p.name);if(name===null)return;const heading=prompt('Page Heading (blank = current heading)',p.heading||'');if(heading===null)return;const order=Number(prompt('Order',String(p.order))||p.order);const visible=confirm('OK = Show page/menu, Cancel = Hide');state.pageOverrides[key]={...(state.pageOverrides[key]||{}),name:name.trim()||p.name,heading:heading.trim(),order,visible,deleted:false};state.menu[key]={...menuCfg(key),label:name.trim()||p.name,order,visible};await persist();refreshAll();message('Existing Admin page updated.','success')}else if(b.dataset.fd!==undefined){const key=b.dataset.fd;if(key==='admineditor')return;const p=fixedPageCfg(key);if(!confirm(`${p.name} page Recycle Bin me bheje? Core code safe rahega.`))return;await trash('adminPage',key,{kind:'fixed',key,page:p,menu:menuCfg(key)});state.pageOverrides[key]={...(state.pageOverrides[key]||{}),deleted:true,visible:false};state.menu[key]={...menuCfg(key),visible:false};await persist();refreshAll();message('Existing Admin page moved to Recycle Bin.','success')}});
document.querySelectorAll('[data-ae-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-ae-tab]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.admin-editor-panel').forEach(x=>x.classList.remove('active'));$(`ae${btn.dataset.aeTab[0].toUpperCase()+btn.dataset.aeTab.slice(1)}Panel`)?.classList.add('active')}));
onSnapshot(doc(db,'settings','adminEditor'),snap=>{const d=snap.exists()?snap.data():{};state={menu:d.menu||{},pageOverrides:d.pageOverrides||{},theme:{...DEF_THEME,...(d.theme||{})},themes:Array.isArray(d.themes)?d.themes:[],customPages:Array.isArray(d.customPages)?d.customPages:[],customMenus:Array.isArray(d.customMenus)?d.customMenus:[]};fillTheme(state.theme);applyTheme(state.theme);refreshAll()},e=>{console.error('Admin Editor load error:',e);message('Admin Editor load error: '+e.message,'danger')});
