import { db } from './firebase-config.js';
import { doc, onSnapshot, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const FIXED=[
 ['dashboard','Dashboard','fa-solid fa-house',10],['admineditor','Admin Editor','fa-solid fa-sliders',20],['updates','Government Updates','fa-solid fa-bullhorn',30],['services','Services','fa-solid fa-toolbox',40],['categories','Categories','fa-solid fa-folder',50],['images','Images','fa-solid fa-image',60],['documents','Documents','fa-solid fa-file-lines',70],['youtube','YouTube','fa-brands fa-youtube',80],['notifications','Notifications','fa-solid fa-bell',90],['analytics','Analytics','fa-solid fa-chart-line',100],['seo','SEO Manager','fa-solid fa-magnifying-glass',110],['pages','Website Pages','fa-solid fa-pen-to-square',120],['sitebuilder','Full Website CMS','fa-solid fa-layer-group',130],['dynamicpages','Page & Menu Builder','fa-solid fa-file-circle-plus',140],['recyclebin','Recycle Bin','fa-solid fa-recycle',150],['themes','Theme Manager','fa-solid fa-palette',160],['settings','Settings','fa-solid fa-gear',170]
];
const DEF_THEME={name:'Original Admin',green:'#00c853',yellow:'#ffd600',pink:'#ff4081',red:'#ff1744',blue:'#2979ff',text:'#111827',bg:'#f4f7fc',panel:'#ffffff',line:'#e5e7eb',side1:'#00c853',side2:'#ff1744',menuText:'#ffffff',radius:18,sidebarWidth:260};
let state={menu:{},theme:{...DEF_THEME},themes:[],customPages:[]}, editCustom=null, editTheme=null;
function message(t,type='info'){if($('aeMessage')){$('aeMessage').textContent=t;$('aeMessage').className='settings-message '+type}}
function menuCfg(key){const d=FIXED.find(x=>x[0]===key);return {...{label:d?.[1]||key,icon:d?.[2]||'fa-solid fa-file',order:d?.[3]||999,visible:true},...(state.menu?.[key]||{})}}
function applyTheme(t=DEF_THEME){const r=document.documentElement;r.style.setProperty('--green',t.green||DEF_THEME.green);r.style.setProperty('--yellow',t.yellow||DEF_THEME.yellow);r.style.setProperty('--pink',t.pink||DEF_THEME.pink);r.style.setProperty('--red',t.red||DEF_THEME.red);r.style.setProperty('--blue',t.blue||DEF_THEME.blue);r.style.setProperty('--black',t.text||DEF_THEME.text);r.style.setProperty('--bg',t.bg||DEF_THEME.bg);r.style.setProperty('--panel',t.panel||DEF_THEME.panel);r.style.setProperty('--line',t.line||DEF_THEME.line);r.style.setProperty('--radius',(Number(t.radius)||18)+'px');r.style.setProperty('--sidebar',(Number(t.sidebarWidth)||260)+'px');r.style.setProperty('--admin-page-bg',t.bg||DEF_THEME.bg);r.style.setProperty('--admin-side-1',t.side1||DEF_THEME.side1);r.style.setProperty('--admin-side-2',t.side2||DEF_THEME.side2);r.style.setProperty('--admin-menu-text',t.menuText||'#fff');document.body.classList.add('admin-editor-themed')}
function applyMenu(){const ul=$('sidebarMenu');if(!ul)return;FIXED.forEach(([key])=>{const li=ul.querySelector(`li[data-page="${key}"]`);if(!li)return;const c=menuCfg(key);li.style.display=c.visible===false?'none':'';li.dataset.aeOrder=String(Number(c.order)||999);const sp=li.querySelector('span');if(sp)sp.textContent=c.label;const i=li.querySelector('i');if(i)i.className=c.icon});
 state.customPages.forEach(x=>ensureCustomPage(x));
 [...ul.querySelectorAll('li[data-page]')].sort((a,b)=>Number(a.dataset.aeOrder||999)-Number(b.dataset.aeOrder||999)).forEach(li=>ul.insertBefore(li,$('logoutBtn')));
}
function ensureCustomPage(x){const key='custom_'+x.id;let sec=$(key+'Page');if(!sec){sec=document.createElement('section');sec.id=key+'Page';sec.className='page admin-custom-page';document.querySelector('.main-content')?.appendChild(sec)}sec.innerHTML=`<div class="page-intro"><div><h2>${esc(x.heading||x.name||'Admin Page')}</h2><p>Custom Admin Page</p></div></div><div class="dashboard-info-box"><div class="ae-custom-content">${esc(x.content||'')}</div></div>`;let li=document.querySelector(`#sidebarMenu li[data-page="${key}"]`);if(!li){li=document.createElement('li');li.dataset.page=key;li.innerHTML='<i></i><span></span>';$('sidebarMenu')?.insertBefore(li,$('logoutBtn'))}li.style.display=x.visible===false?'none':'';li.dataset.aeOrder=String(Number(x.order)||900);li.querySelector('i').className=x.icon||'fa-solid fa-file';li.querySelector('span').textContent=x.name||'Admin Page'}
function renderMenu(){const b=$('aeMenuList');if(!b)return;b.innerHTML=FIXED.map(([key])=>{const c=menuCfg(key);return `<div class="ae-menu-row" data-key="${key}"><div class="ae-icon-preview"><i class="${esc(c.icon)}"></i></div><input class="ae-label" value="${esc(c.label)}" aria-label="Menu name"><input class="ae-icon-input" value="${esc(c.icon)}" aria-label="Icon"><input class="ae-order" type="number" value="${Number(c.order)}" aria-label="Order"><select class="ae-visible"><option value="true" ${c.visible!==false?'selected':''}>Show</option><option value="false" ${c.visible===false?'selected':''}>Hide</option></select></div>`}).join('')}
function collectMenu(){const out={};document.querySelectorAll('.ae-menu-row').forEach(r=>{out[r.dataset.key]={label:r.querySelector('.ae-label').value.trim()||r.dataset.key,icon:r.querySelector('.ae-icon-input').value.trim()||'fa-solid fa-file',order:Number(r.querySelector('.ae-order').value||999),visible:r.querySelector('.ae-visible').value!=='false'}});return out}
function themeFromForm(){return {name:$('aeThemeName').value.trim()||'Admin Theme',green:$('aeGreen').value,yellow:$('aeYellow').value,pink:$('aePink').value,red:$('aeRed').value,blue:$('aeBlue').value,text:$('aeText').value,bg:$('aeBg').value,panel:$('aePanel').value,line:$('aeLine').value,side1:$('aeSide1').value,side2:$('aeSide2').value,menuText:$('aeMenuText').value,radius:Number($('aeRadius').value||18),sidebarWidth:Number($('aeSidebarWidth').value||260)}}
function fillTheme(t=DEF_THEME){for(const [id,k] of Object.entries({aeThemeName:'name',aeGreen:'green',aeYellow:'yellow',aePink:'pink',aeRed:'red',aeBlue:'blue',aeText:'text',aeBg:'bg',aePanel:'panel',aeLine:'line',aeSide1:'side1',aeSide2:'side2',aeMenuText:'menuText',aeRadius:'radius',aeSidebarWidth:'sidebarWidth'}))if($(id))$(id).value=t[k]??DEF_THEME[k]}
function renderThemes(){const b=$('aeThemeList');if(!b)return;b.innerHTML=state.themes.length?state.themes.map((t,i)=>`<article class="content-card"><h3>${esc(t.name||'Admin Theme')}</h3><div class="ae-theme-swatch" style="--ae1:${esc(t.green)};--ae2:${esc(t.blue)};--ae3:${esc(t.pink)};--ae4:${esc(t.red)}"></div><div class="card-actions"><button class="action-btn edit" data-te="${i}">✏ Edit</button><button class="action-btn copy" data-ta="${i}">✓ Apply</button><button class="action-btn delete" data-td="${i}">🗑 Delete</button></div></article>`).join(''):'<div class="empty-state">No saved Admin themes.</div>'}
function clearCustom(){editCustom=null;for(const id of ['aePageName','aePageHeading','aePageContent'])if($(id))$(id).value='';if($('aePageIcon'))$('aePageIcon').value='fa-solid fa-file';if($('aePageOrder'))$('aePageOrder').value='90';if($('aePageVisible'))$('aePageVisible').value='true';if($('aeSavePage'))$('aeSavePage').textContent='Save Admin Page'}
function renderCustom(){const b=$('aeCustomList');if(!b)return;b.innerHTML=state.customPages.length?state.customPages.map((x,i)=>`<article class="content-card"><span class="status-badge ${x.visible===false?'draft':'published'}">${x.visible===false?'Hidden':'Visible'}</span><h3><i class="${esc(x.icon||'fa-solid fa-file')}"></i> ${esc(x.name||'Admin Page')}</h3><p>${esc(x.heading||'')}</p><small>Order ${Number(x.order||90)}</small><div class="card-actions"><button class="action-btn edit" data-ce="${i}">✏ Edit</button><button class="action-btn delete" data-cd="${i}">🗑 Delete</button></div></article>`).join(''):'<div class="empty-state">No custom Admin pages.</div>'}
async function persist(extra={}){state={...state,...extra};await setDoc(doc(db,'settings','adminEditor'),{...state,updatedAt:serverTimestamp()},{merge:false})}
$('aeSaveMenu')?.addEventListener('click',async()=>{state.menu=collectMenu();await persist();applyMenu();message('Admin menu saved & applied.','success')});
$('aeResetMenu')?.addEventListener('click',async()=>{if(!confirm('Original Admin menu names/order/show restore karein?'))return;state.menu={};await persist();renderMenu();applyMenu();message('Original menu restored.','success')});
$('aePreviewTheme')?.addEventListener('click',()=>applyTheme(themeFromForm()));
$('aeSaveTheme')?.addEventListener('click',async()=>{const t=themeFromForm();if(editTheme!==null)state.themes[editTheme]=t;else state.themes.push(t);state.theme=t;editTheme=null;await persist();applyTheme(t);renderThemes();message('Admin theme saved & applied.','success')});
$('aeResetTheme')?.addEventListener('click',async()=>{fillTheme(DEF_THEME);state.theme={...DEF_THEME};await persist();applyTheme(DEF_THEME);message('Original Admin theme restored.','success')});
$('aeThemeList')?.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.te!==undefined){editTheme=Number(b.dataset.te);fillTheme(state.themes[editTheme]);document.querySelector('[data-ae-tab="theme"]')?.click()}else if(b.dataset.ta!==undefined){state.theme={...state.themes[Number(b.dataset.ta)]};await persist();fillTheme(state.theme);applyTheme(state.theme);message('Theme applied.','success')}else if(b.dataset.td!==undefined){const i=Number(b.dataset.td);if(!confirm('Saved Admin theme delete karein?'))return;state.themes.splice(i,1);await persist();renderThemes();message('Theme deleted.','success')}});
$('aeSavePage')?.addEventListener('click',async()=>{const name=$('aePageName').value.trim();if(!name)return alert('Page Name required.');const x={id:editCustom!==null?state.customPages[editCustom].id:'p'+Date.now(),name,icon:$('aePageIcon').value.trim()||'fa-solid fa-file',heading:$('aePageHeading').value.trim()||name,content:$('aePageContent').value.trim(),order:Number($('aePageOrder').value||90),visible:$('aePageVisible').value!=='false'};if(editCustom!==null)state.customPages[editCustom]=x;else state.customPages.push(x);await persist();clearCustom();renderCustom();applyMenu();message('Admin page saved.','success')});
$('aeClearPage')?.addEventListener('click',clearCustom);
$('aeCustomList')?.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.ce!==undefined){editCustom=Number(b.dataset.ce);const x=state.customPages[editCustom];$('aePageName').value=x.name||'';$('aePageIcon').value=x.icon||'';$('aePageHeading').value=x.heading||'';$('aePageContent').value=x.content||'';$('aePageOrder').value=x.order??90;$('aePageVisible').value=String(x.visible!==false);$('aeSavePage').textContent='Update Admin Page'}else if(b.dataset.cd!==undefined){const i=Number(b.dataset.cd);if(!confirm('Custom Admin page delete karein?'))return;const old=state.customPages[i];state.customPages.splice(i,1);document.querySelector(`#sidebarMenu li[data-page="custom_${old.id}"]`)?.remove();$('custom_'+old.id+'Page')?.remove();await persist();renderCustom();message('Custom Admin page deleted.','success')}});
document.querySelectorAll('[data-ae-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-ae-tab]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.admin-editor-panel').forEach(x=>x.classList.remove('active'));$(`ae${btn.dataset.aeTab[0].toUpperCase()+btn.dataset.aeTab.slice(1)}Panel`)?.classList.add('active')}));
onSnapshot(doc(db,'settings','adminEditor'),snap=>{const d=snap.exists()?snap.data():{};state={menu:d.menu||{},theme:{...DEF_THEME,...(d.theme||{})},themes:Array.isArray(d.themes)?d.themes:[],customPages:Array.isArray(d.customPages)?d.customPages:[]};fillTheme(state.theme);renderMenu();renderThemes();renderCustom();applyTheme(state.theme);applyMenu()},e=>{console.error('Admin Editor load error:',e);message('Admin Editor load error: '+e.message,'danger')});
