export const DEFAULT_SERVICES = [
  ['Aadhaar New Enrolment Guidance','Aadhaar','🪪'],['Aadhaar Address Update','Aadhaar','🏠'],['Aadhaar Mobile Number Update Guidance','Aadhaar','📱'],['Aadhaar PVC Card Order','Aadhaar','💳'],['Aadhaar Download / Print','Aadhaar','🖨️'],['Aadhaar Status Check','Aadhaar','🔎'],
  ['PAN Card New Application','PAN Card','💳'],['PAN Card Correction','PAN Card','✏️'],['PAN Card Reprint','PAN Card','🖨️'],['PAN-Aadhaar Link Assistance','PAN Card','🔗'],
  ['Voter ID New Registration','Voter ID','🗳️'],['Voter ID Correction','Voter ID','✏️'],['Voter ID Address Change','Voter ID','🏠'],['Voter ID Download','Voter ID','⬇️'],['Voter ID Status Check','Voter ID','🔎'],
  ['Ayushman Bharat Card','Ayushman','❤️'],['Ayushman Card Download','Ayushman','⬇️'],['Ayushman Beneficiary Search','Ayushman','🔎'],['ABHA Health ID','ABHA','🏥'],['ABHA Card Download','ABHA','⬇️'],
  ['e-Shram Card Registration','Labour','👷'],['e-Shram Card Update','Labour','✏️'],['e-Shram Card Download','Labour','⬇️'],['Labour Card Assistance','Labour','🧰'],
  ['Maha ID Registration','Maha ID','🆔'],['Maha ID Update','Maha ID','✏️'],['Maha ID Download / Print','Maha ID','🖨️'],
  ['Income Certificate','Certificates','📜'],['Caste Certificate','Certificates','📜'],['Non-Creamy Layer Certificate','Certificates','📜'],['Domicile Certificate','Certificates','📜'],['Residence Certificate','Certificates','📜'],['Nationality Certificate','Certificates','📜'],['Birth Certificate Assistance','Certificates','👶'],['Death Certificate Assistance','Certificates','🕯️'],['Marriage Certificate Assistance','Certificates','💍'],
  ['Driving Licence Application','RTO','🚗'],['Driving Licence Renewal','RTO','🔄'],['Learning Licence','RTO','🚦'],['RC Services','RTO','📘'],['Vehicle Transfer Assistance','RTO','🔁'],['Vehicle Insurance Assistance','RTO','🛡️'],['PUC Information','RTO','🌿'],['e-Challan Check','RTO','🧾'],
  ['Passport Application Assistance','Passport','🛂'],['Passport Appointment Assistance','Passport','📅'],['Police Verification Guidance','Passport','👮'],
  ['PM Kisan Registration Assistance','Agriculture','🌾'],['PM Kisan eKYC Assistance','Agriculture','✅'],['PM Kisan Status Check','Agriculture','🔎'],['Crop Insurance Assistance','Agriculture','🌱'],['Farmer Registration Assistance','Agriculture','👨‍🌾'],['Agriculture Scheme Form Assistance','Agriculture','🚜'],
  ['Scholarship Form Assistance','Scholarship','🎓'],['MahaDBT Scholarship Assistance','Scholarship','🎓'],['Scholarship Status Check','Scholarship','🔎'],['Education Certificate Upload Help','Scholarship','📚'],
  ['Bank Account Opening Guidance','Banking','🏦'],['AEPS Service','Banking','💵'],['Money Transfer Assistance','Banking','💸'],['Pension Life Certificate Guidance','Banking','👴'],['Jeevan Pramaan Assistance','Banking','📜'],
  ['Electricity Bill Payment','Bill Payment','⚡'],['Mobile Recharge','Bill Payment','📱'],['DTH Recharge','Bill Payment','📺'],['FASTag Recharge Assistance','Bill Payment','🚘'],['Water Bill Payment Assistance','Bill Payment','💧'],
  ['Online Form Filling','Online Service','📝'],['Exam Form Filling','Online Service','🎯'],['Job Application Form','Online Service','💼'],['Hall Ticket Download','Online Service','🎫'],['Result Download','Online Service','📊'],['DigiLocker Assistance','Online Service','🔐'],['PDF / Scan / Print Service','Online Service','🖨️'],['Passport Size Photo','Online Service','📷'],['Lamination Service','Online Service','🧾'],['PVC Card Printing','Online Service','💳']
].map(([name,category,icon])=>({name,category,icon,description:`${name} ke liye online process, document guidance aur application assistance available.`}));

export const DEFAULT_SCHEMES = [
  ['Mukhyamantri Majhi Ladki Bahin Yojana','Women','👩'],['Lek Ladki Yojana','Women','👧'],['PM Ujjwala Yojana Assistance','Women','🔥'],['MahaDBT Scholarship Schemes','Education','🎓'],['Post Matric Scholarship Assistance','Education','📚'],['Pre Matric Scholarship Assistance','Education','📘'],['PM Kisan Samman Nidhi','Farmer','🌾'],['Namo Shetkari Mahasanman Nidhi','Farmer','🚜'],['Crop Insurance / PMFBY Assistance','Farmer','🌱'],['Agriculture Subsidy / MahaDBT Farmer','Farmer','🧑‍🌾'],['Sanjay Gandhi Niradhar Anudan Yojana','Social Welfare','🤝'],['Shravan Bal Seva Rajya Nivruttivetan Yojana','Senior Citizen','👴'],['Indira Gandhi National Old Age Pension Assistance','Senior Citizen','👵'],['Indira Gandhi National Widow Pension Assistance','Social Welfare','🕊️'],['Indira Gandhi National Disability Pension Assistance','Divyang','♿'],['Ayushman Bharat / PM-JAY','Health','🏥'],['Mahatma Jyotirao Phule Jan Arogya Yojana Assistance','Health','❤️'],['Pradhan Mantri Awas Yojana Assistance','Housing','🏠'],['Ramai Awas Yojana Assistance','Housing','🏡'],['PM Vishwakarma Yojana Assistance','Employment','🛠️'],['PM SVANidhi Assistance','Employment','🛒'],['Mudra Loan Guidance','Employment','💼'],['Skill Development Scheme Guidance','Employment','🎯'],['Labour Welfare Scheme Assistance','Labour','👷'],['Ration Card / Food Security Assistance','Food','🍚'],['Maha ID Related Government Service Assistance','Digital Maharashtra','🆔']
].map(([name,category,icon])=>({name,category:`Yojana - ${category}`,icon,description:`${name} ke liye eligibility, required documents, online application aur status guidance.`}));

export const DEFAULT_DIVYANG = [
  ['UDID Card New Registration','Divyang','🪪'],['UDID Card Renewal / Update Assistance','Divyang','🔄'],['UDID Card Download / Print','Divyang','⬇️'],['UDID Application Status Check','Divyang','🔎'],['Disability Certificate Application Guidance','Divyang','📜'],['Disability Certificate Download Guidance','Divyang','⬇️'],['Divyang Portal Registration','Divyang','🌐'],['Divyang Pension Application Assistance','Divyang','💰'],['Divyang Pension Status Check','Divyang','🔎'],['Disability Scholarship Assistance','Divyang','🎓'],['Divyang Student Scheme Guidance','Divyang','📚'],['Assistive Device Scheme Guidance','Divyang','🦽'],['ADIP Scheme Guidance','Divyang','🦯'],['Railway Concession Certificate Guidance','Divyang','🚆'],['Bus Concession Guidance','Divyang','🚌'],['Income / Caste / Domicile Certificate for Divyang Schemes','Divyang','📑'],['Divyang Employment Registration Guidance','Divyang','💼'],['Self Employment / Loan Scheme Guidance','Divyang','🏦'],['Marriage Incentive Scheme Guidance','Divyang','💍'],['Divyang Government Scheme Eligibility Check','Divyang','✅']
].map(([name,category,icon])=>({name,category,icon,description:`${name} ke liye form, document list, online process aur WhatsApp assistance available.`}));

export const DOCUMENT_CHECKLISTS = [
  {title:'Aadhaar Services',category:'Aadhaar',items:['Aadhaar number / Aadhaar copy','Registered mobile number where required','Address proof for address update','Supporting identity/address document as applicable']},
  {title:'PAN Card',category:'PAN Card',items:['Aadhaar card','Passport size photo where required','Signature','Mobile number & email','Date of birth proof if required']},
  {title:'Voter ID',category:'Voter ID',items:['Aadhaar / identity proof','Age proof','Address proof','Passport size photo','Mobile number']},
  {title:'Ayushman Bharat Card',category:'Ayushman',items:['Aadhaar card','Eligible family/ration details','Mobile number','Beneficiary details']},
  {title:'ABHA Health ID',category:'ABHA',items:['Aadhaar card or supported ID','Mobile number','Basic personal details']},
  {title:'e-Shram Card',category:'Labour',items:['Aadhaar card','Aadhaar-linked mobile number','Bank passbook/account details','Occupation details']},
  {title:'Maha ID',category:'Maha ID',items:['Aadhaar card','Mobile number','Basic personal information','Additional proof if portal asks']},
  {title:'Income Certificate',category:'Certificates',items:['Aadhaar card','Ration card / family details','Income proof or declaration','Residence proof','Photo']},
  {title:'Caste Certificate',category:'Certificates',items:['Aadhaar card','School leaving / birth related proof','Father/relative caste proof where applicable','Residence proof','Old records/supporting documents']},
  {title:'Non-Creamy Layer Certificate',category:'Certificates',items:['Caste certificate','Income proof','Aadhaar card','Residence proof','Relevant family documents']},
  {title:'Domicile Certificate',category:'Certificates',items:['Aadhaar card','Residence proof','School leaving / birth proof','Ration card or family proof','Photo']},
  {title:'Driving Licence / Learning Licence',category:'RTO',items:['Aadhaar / identity proof','Address proof','Age proof','Passport size photo','Existing licence for renewal']},
  {title:'Passport Application',category:'Passport',items:['Aadhaar card','Date of birth proof','Address proof','PAN / other supporting ID where applicable','Appointment/application details']},
  {title:'PM Kisan',category:'Farmer',items:['Aadhaar card','Land record / 7/12 as applicable','Bank passbook','Mobile number','Farmer details']},
  {title:'MahaDBT Farmer Schemes',category:'Farmer',items:['Aadhaar card','Farmer registration details','Land record','Bank passbook','Scheme-specific quotation/document if required']},
  {title:'Ladki Bahin Yojana',category:'Women',items:['Aadhaar card','Bank account/passbook','Mobile number','Residence/domicile proof as applicable','Income/family eligibility documents as required']},
  {title:'Scholarship / MahaDBT',category:'Education',items:['Aadhaar card','Student bank passbook','Income certificate','Caste certificate if applicable','Previous marksheet','Admission/bonafide/fee receipt','Domicile/residence documents as applicable']},
  {title:'UDID Card',category:'Divyang',items:['Aadhaar card','Passport size photo','Signature/thumb impression as applicable','Existing disability certificate/medical records if available','Address proof','Mobile number']},
  {title:'Disability Certificate',category:'Divyang',items:['Aadhaar card','Passport size photo','Medical records/reports','Address proof','Mobile number','Hospital/medical board related documents as asked']},
  {title:'Divyang Pension',category:'Divyang',items:['Aadhaar card','Disability certificate / UDID','Bank passbook','Income certificate','Residence proof','Passport size photo','Scheme-specific declaration/eligibility proof']},
  {title:'Divyang Scholarship',category:'Divyang',items:['Aadhaar card','UDID / disability certificate','Student bank passbook','Income certificate','Bonafide/admission proof','Previous marksheet','Fee receipt where applicable']},
  {title:'Sanjay Gandhi Niradhar Yojana',category:'Social Welfare',items:['Aadhaar card','Bank passbook','Income certificate','Residence proof','Age/condition related supporting document','Passport size photo']},
  {title:'Old Age Pension',category:'Senior Citizen',items:['Aadhaar card','Age proof','Bank passbook','Income certificate','Residence proof','Passport size photo']},
  {title:'Widow Pension',category:'Social Welfare',items:['Aadhaar card','Spouse death certificate','Bank passbook','Income certificate','Residence proof','Passport size photo']},
  {title:'Ration Card Services',category:'Food',items:['Aadhaar cards of family members','Residence proof','Existing ration card if applicable','Family details','Mobile number']}
];
