import {moveToTrash} from './trash.js';
import {db} from './supabase-app.js';import {collection,addDoc,doc,updateDoc,onSnapshot,serverTimestamp} from './supabase-db.js';
const $=id=>document.getElementById(id),e=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');let rows=[],id=null;
function clear(){id=null;$('checklistTitle').value='';$('checklistCategory').value='';$('checklistItems').value='';$('checklistStatus').value='Published';$('saveChecklist').textContent='Save Checklist'}
function render(){const b=$('checklistsList');if(!b)return;b.innerHTML=rows.length?rows.map(x=>`<article class="content-card"><span class="status-badge ${(x.status||'Published').toLowerCase()}">${e(x.status||'Published')}</span><h3>${e(x.title)}</h3><small>${e(x.category||'')}</small><p>${(x.items||[]).map(i=>'• '+e(i)).join('<br>')}</p><div class="card-actions"><button class="action-btn edit" data-a="e" data-id="${x.id}">✏ Edit</button><button class="action-btn delete" data-a="d" data-id="${x.id}">🗑 Delete</button></div></article>`).join(''):'<div class="empty-state">No editable checklists.</div>'}
async function save(){const title=$('checklistTitle').value.trim(),category=$('checklistCategory').value.trim(),items=$('checklistItems').value.split('\n').map(x=>x.trim()).filter(Boolean),status=$('checklistStatus').value;if(!title||!items.length)return alert('Title aur documents dalo.');if(rows.find(x=>x.id!==id&&String(x.title||'').trim().toLowerCase()===title.toLowerCase()))return alert('Duplicate checklist not allowed.');const d={title,category,items,status,updatedAt:serverTimestamp()};id?await updateDoc(doc(db,'documentChecklists',id),d):await addDoc(collection(db,'documentChecklists'),{...d,createdAt:serverTimestamp()});clear()}
function edit(k){const x=rows.find(z=>z.id===k);if(!x)return;id=k;$('checklistTitle').value=x.title||'';$('checklistCategory').value=x.category||'';$('checklistItems').value=(x.items||[]).join('\n');$('checklistStatus').value=x.status||'Published';$('saveChecklist').textContent='Update Checklist'}
async function del(k){const x=rows.find(z=>z.id===k);if(x&&confirm('Checklist Recycle Bin me bhejna hai?'))await moveToTrash('documentChecklists',k,x)}
$('saveChecklist')?.addEventListener('click',save);$('checklistsList')?.addEventListener('click',x=>{const b=x.target.closest('button[data-a]');if(b)(b.dataset.a==='e'?edit(b.dataset.id):del(b.dataset.id))});onSnapshot(collection(db,'documentChecklists'),s=>{rows=s.docs.map(d=>({id:d.id,...d.data()}));render()});
