import { db } from './firebase-config.js';
import { collection, addDoc, doc, updateDoc, deleteDoc, onSnapshot, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const slugify=v=>String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const clean=v=>{if(Array.isArray(v))return v.filter(x=>x!==undefined).map(clean);if(v&&typeof v==='object'&&!(v instanceof Date)){const o={};for(const [k,x] of Object.entries(v))if(x!==undefined&&k!=='id')o[k]=clean(x);return o}return v};
let pages=[],sections=[],menus=[],editPageId=null,editSectionId=null,editMenuId=null;
function resetPage(){editPageId=null;['dpName','dpSlug','dpTitle','dpText'].forEach(id=>{if($(id))$(id).value=''});if($('dpC1'))$('dpC1').value='#ec4899';if($('dpC2'))$('dpC2').value='#2563eb';if($('dpMenu'))$('dpMenu').value='true';if($('dpOrder'))$('dpOrder').value='50';if($('dpStatus'))$('dpStatus').value='Published';if($('dpSave'))$('dpSave').textContent='Save Page'}
function resetSection(){editSectionId=null;['dsTitle','dsText','dsImage','dsButton','dsLink'].forEach(id=>{if($(id))$(id).value=''});if($('dsBg'))$('dsBg').value='#ffffff';if($('dsColor'))$('dsColor').value='#132238';if($('dsAccent'))$('dsAccent').value='#ec4899';if($('dsOrder'))$('dsOrder').value='50';if($('dsSave'))$('dsSave').textContent='Save Section'}
function resetMenu(){editMenuId=null;['emName','emLink'].forEach(id=>{if($(id))$(id).value=''});if($('emOrder'))$('emOrder').value='80';if($('emVisible'))$('emVisible').value='true';if($('emSave'))$('emSave').textContent='Save Menu'}
$('dpName')?.addEventListener('input',()=>{if(!editPageId&&$('dpSlug'))$('dpSlug').value=slugify($('dpName').value)});
async function trash(type,id,data){const payload={type,sourceId:id,data:clean(data||{}),deletedAt:serverTimestamp()};await addDoc(collection(db,'recycleBin'),payload);await deleteDoc(doc(db,type,id));}
async function savePage(){const name=$('dpName')?.value.trim()||'',slug=slugify($('dpSlug')?.value||name);if(!name||!slug)return alert('Page Name aur URL Slug required.');if(pages.some(x=>x.id!==editPageId&&x.slug===slug))return alert('Ye URL Slug already use ho raha hai.');const data={name,slug,title:$('dpTitle')?.value.trim()||name,subtitle:$('dpText')?.value.trim()||'',color1:$('dpC1')?.value||'#ec4899',color2:$('dpC2')?.value||'#2563eb',inMenu:$('dpMenu')?.value!=='false',order:Number($('dpOrder')?.value||50),status:$('dpStatus')?.value||'Published',updatedAt:serverTimestamp()};try{if(editPageId)await updateDoc(doc(db,'dynamicPages',editPageId),data);else await addDoc(collection(db,'dynamicPages'),{...data,createdAt:serverTimestamp()});resetPage()}catch(e){console.error(e);alert(e.message)}}
function editPage(id){const x=pages.find(v=>v.id===id);if(!x)return;editPageId=id;$('dpName').value=x.name||'';$('dpSlug').value=x.slug||'';$('dpTitle').value=x.title||'';$('dpText').value=x.subtitle||x.text||'';$('dpC1').value=x.color1||'#ec4899';$('dpC2').value=x.color2||'#2563eb';$('dpMenu').value=String(x.inMenu!==false);$('dpOrder').value=x.order??x.menuOrder??50;$('dpStatus').value=x.status||'Published';$('dpSave').textContent='Update Page'}
async function removePage(id){const x=pages.find(v=>v.id===id);if(!x||!confirm(`"${x.name||'Page'}" Recycle Bin me bhejna hai?`))return;try{for(const s of sections.filter(v=>v.pageId===id))await trash('dynamicSections',s.id,s);await trash('dynamicPages',id,x)}catch(e){console.error(e);alert('Delete failed: '+e.message)}}
function renderPages(){const b=$('dpList');if(!b)return;b.innerHTML=pages.length?pages.slice().sort((a,b)=>Number(a.order??a.menuOrder??50)-Number(b.order??b.menuOrder??50)).map(x=>`<article class="content-card"><span class="status-badge ${(x.status||'Published').toLowerCase()}">${esc(x.status||'Published')}</span><h3>${esc(x.name||x.title||'Page')}</h3><p>dynamic-page.html?page=${encodeURIComponent(x.slug||'')}</p><small>${x.inMenu!==false?'Menu ON':'Menu OFF'} · Order ${Number(x.order??x.menuOrder??50)}</small><div class="card-actions"><a class="action-btn copy" target="_blank" href="dynamic-page.html?page=${encodeURIComponent(x.slug||'')}">👁 Open</a><button class="action-btn edit" data-pe="${x.id}">✏ Edit</button><button class="action-btn delete" data-pd="${x.id}">🗑 Delete</button></div></article>`).join(''):'<div class="empty-state">No custom pages.</div>';fillPages()}
function fillPages(){const old=$('dsPage')?.value||'';if($('dsPage')){$('dsPage').innerHTML='<option value="">Select Page</option>'+pages.map(x=>`<option value="${x.id}">${esc(x.name||x.title||'Page')}</option>`).join('');if(old)$('dsPage').value=old}}
async function saveSection(){const pageId=$('dsPage')?.value||'',title=$('dsTitle')?.value.trim()||'';if(!pageId||!title)return alert('Page aur Section Title required.');const data={pageId,title,text:$('dsText')?.value.trim()||'',imageUrl:$('dsImage')?.value.trim()||'',buttonText:$('dsButton')?.value.trim()||'',buttonLink:$('dsLink')?.value.trim()||'',bg:$('dsBg')?.value||'#ffffff',color:$('dsColor')?.value||'#132238',accent:$('dsAccent')?.value||'#ec4899',order:Number($('dsOrder')?.value||50),visible:true,updatedAt:serverTimestamp()};try{if(editSectionId)await updateDoc(doc(db,'dynamicSections',editSectionId),data);else await addDoc(collection(db,'dynamicSections'),{...data,createdAt:serverTimestamp()});resetSection()}catch(e){console.error(e);alert(e.message)}}
function editSection(id){const x=sections.find(v=>v.id===id);if(!x)return;editSectionId=id;$('dsPage').value=x.pageId||'';$('dsTitle').value=x.title||'';$('dsText').value=x.text||'';$('dsImage').value=x.imageUrl||'';$('dsButton').value=x.buttonText||'';$('dsLink').value=x.buttonLink||'';$('dsBg').value=x.bg||'#ffffff';$('dsColor').value=x.color||'#132238';$('dsAccent').value=x.accent||'#ec4899';$('dsOrder').value=x.order??50;$('dsSave').textContent='Update Section'}
async function removeSection(id){const x=sections.find(v=>v.id===id);if(!x||!confirm('Section Recycle Bin me bhejna hai?'))return;try{await trash('dynamicSections',id,x)}catch(e){console.error(e);alert('Delete failed: '+e.message)}}
function renderSections(){const b=$('dsList');if(!b)return;b.innerHTML=sections.length?sections.slice().sort((a,b)=>Number(a.order||0)-Number(b.order||0)).map(x=>`<article class="content-card"><h3>${esc(x.title||'Section')}</h3><small>${esc(pages.find(p=>p.id===x.pageId)?.name||'Unknown Page')} · Order ${Number(x.order||0)}</small><p>${esc(x.text||'')}</p><div class="card-actions"><button class="action-btn edit" data-se="${x.id}">✏ Edit</button><button class="action-btn delete" data-sd="${x.id}">🗑 Delete</button></div></article>`).join(''):'<div class="empty-state">No sections.</div>'}
async function saveMenu(){const name=$('emName')?.value.trim()||'',link=$('emLink')?.value.trim()||'';if(!name||!link)return alert('Menu Name aur Link required.');const data={name,link,order:Number($('emOrder')?.value||80),visible:$('emVisible')?.value!=='false',updatedAt:serverTimestamp()};try{if(editMenuId)await updateDoc(doc(db,'menuItems',editMenuId),data);else await addDoc(collection(db,'menuItems'),{...data,createdAt:serverTimestamp()});resetMenu()}catch(e){console.error(e);alert(e.message)}}
function editMenu(id){const x=menus.find(v=>v.id===id);if(!x)return;editMenuId=id;$('emName').value=x.name||'';$('emLink').value=x.link||'';$('emOrder').value=x.order??80;$('emVisible').value=String(x.visible!==false);$('emSave').textContent='Update Menu'}
async function removeMenu(id){const x=menus.find(v=>v.id===id);if(!x||!confirm('Menu Recycle Bin me bhejna hai?'))return;try{await trash('menuItems',id,x)}catch(e){console.error(e);alert('Delete failed: '+e.message)}}
function renderMenus(){const b=$('emList');if(!b)return;b.innerHTML=menus.length?menus.slice().sort((a,b)=>Number(a.order||0)-Number(b.order||0)).map(x=>`<article class="content-card"><h3>${esc(x.name||'Menu')}</h3><p>${esc(x.link||'')}</p><small>${x.visible!==false?'Visible':'Hidden'} · Order ${Number(x.order||0)}</small><div class="card-actions"><button class="action-btn edit" data-me="${x.id}">✏ Edit</button><button class="action-btn delete" data-md="${x.id}">🗑 Delete</button></div></article>`).join(''):'<div class="empty-state">No extra menu.</div>'}
$('dpSave')?.addEventListener('click',savePage);$('dpClear')?.addEventListener('click',resetPage);$('dsSave')?.addEventListener('click',saveSection);$('dsClear')?.addEventListener('click',resetSection);$('emSave')?.addEventListener('click',saveMenu);$('emClear')?.addEventListener('click',resetMenu);
$('dpList')?.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.pe)editPage(b.dataset.pe);if(b?.dataset.pd)removePage(b.dataset.pd)});$('dsList')?.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.se)editSection(b.dataset.se);if(b?.dataset.sd)removeSection(b.dataset.sd)});$('emList')?.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.me)editMenu(b.dataset.me);if(b?.dataset.md)removeMenu(b.dataset.md)});
onSnapshot(collection(db,'dynamicPages'),s=>{pages=s.docs.map(d=>({id:d.id,...d.data()}));renderPages();renderSections()},e=>{console.error('dynamicPages:',e);if($('dpList'))$('dpList').innerHTML=`<div class="empty-state">${esc(e.message)}</div>`});
onSnapshot(collection(db,'dynamicSections'),s=>{sections=s.docs.map(d=>({id:d.id,...d.data()}));renderSections()},e=>{console.error('dynamicSections:',e)});
onSnapshot(collection(db,'menuItems'),s=>{menus=s.docs.map(d=>({id:d.id,...d.data()}));renderMenus()},e=>{console.error('menuItems:',e)});
