import {db} from './firebase-config.js';
import {collection,addDoc,doc,updateDoc,deleteDoc,onSnapshot,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'),slug=v=>String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');let pages=[],sections=[],pe=null,se=null;
function clearP(){pe=null;['dpName','dpSlug','dpTitle','dpText'].forEach(i=>$(i).value='');$('dpC1').value='#ec4899';$('dpC2').value='#2563eb';$('dpMenu').value='true';$('dpOrder').value=50;$('dpStatus').value='Published';$('dpSave').textContent='Save Page'}
function clearS(){se=null;['dsTitle','dsText','dsImage','dsButton','dsLink'].forEach(i=>$(i).value='');$('dsBg').value='#ffffff';$('dsColor').value='#132238';$('dsAccent').value='#ec4899';$('dsOrder').value=50;$('dsSave').textContent='Save Section'}
$('dpName')?.addEventListener('input',()=>{if(!pe){$('dpSlug').value=slug($('dpName').value);$('dpTitle').value=$('dpName').value}});
async function saveP(){let name=$('dpName').value.trim(),sl=slug($('dpSlug').value||name);if(!name||!sl)return alert('Page Name required');if(pages.some(x=>x.id!==pe&&x.slug===sl))return alert('Duplicate slug not allowed');let d={name,slug:sl,title:$('dpTitle').value.trim()||name,text:$('dpText').value.trim(),c1:$('dpC1').value,c2:$('dpC2').value,inMenu:$('dpMenu').value==='true',order:Number($('dpOrder').value||50),status:$('dpStatus').value,updatedAt:serverTimestamp()};pe?await updateDoc(doc(db,'dynamicPages',pe),d):await addDoc(collection(db,'dynamicPages'),{...d,createdAt:serverTimestamp()});clearP()}
function editP(id){let x=pages.find(v=>v.id===id);pe=id;$('dpName').value=x.name||'';$('dpSlug').value=x.slug||'';$('dpTitle').value=x.title||'';$('dpText').value=x.text||'';$('dpC1').value=x.c1||'#ec4899';$('dpC2').value=x.c2||'#2563eb';$('dpMenu').value=String(x.inMenu!==false);$('dpOrder').value=x.order??50;$('dpStatus').value=x.status||'Published';$('dpSave').textContent='Update Page'}
async function delP(id){if(!confirm('Page delete?'))return;for(const x of sections.filter(v=>v.pageId===id))await deleteDoc(doc(db,'dynamicSections',x.id));await deleteDoc(doc(db,'dynamicPages',id))}
function renderP(){let b=$('dpList');if(!b)return;b.innerHTML=pages.length?pages.sort((a,b)=>Number(a.order||0)-Number(b.order||0)).map(x=>`<article class="content-card"><span class="status-badge ${(x.status||'Published').toLowerCase()}">${esc(x.status||'Published')}</span><h3>${esc(x.name)}</h3><p>dynamic-page.html?page=${esc(x.slug)}</p><div class="card-actions"><a class="action-btn copy" target="_blank" href="dynamic-page.html?page=${encodeURIComponent(x.slug)}">👁 Open</a><button data-pe="${x.id}" class="action-btn edit">✏ Edit</button><button data-pd="${x.id}" class="action-btn delete">🗑 Delete</button></div></article>`).join(''):'<div class="empty-state">No custom pages.</div>';let v=$('dsPage')?.value;$('dsPage').innerHTML='<option value="">Select Page</option>'+pages.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');if(v)$('dsPage').value=v}
async function saveS(){let pageId=$('dsPage').value,title=$('dsTitle').value.trim();if(!pageId||!title)return alert('Page + title required');let d={pageId,title,text:$('dsText').value.trim(),image:$('dsImage').value.trim(),button:$('dsButton').value.trim(),link:$('dsLink').value.trim(),bg:$('dsBg').value,color:$('dsColor').value,accent:$('dsAccent').value,order:Number($('dsOrder').value||50),updatedAt:serverTimestamp()};se?await updateDoc(doc(db,'dynamicSections',se),d):await addDoc(collection(db,'dynamicSections'),{...d,createdAt:serverTimestamp()});clearS()}
function editS(id){let x=sections.find(v=>v.id===id);se=id;$('dsPage').value=x.pageId;$('dsTitle').value=x.title||'';$('dsText').value=x.text||'';$('dsImage').value=x.image||'';$('dsButton').value=x.button||'';$('dsLink').value=x.link||'';$('dsBg').value=x.bg||'#fff';$('dsColor').value=x.color||'#132238';$('dsAccent').value=x.accent||'#ec4899';$('dsOrder').value=x.order??50;$('dsSave').textContent='Update Section'}
async function delS(id){if(confirm('Section delete?'))await deleteDoc(doc(db,'dynamicSections',id))}
function renderS(){let b=$('dsList');if(!b)return;b.innerHTML=sections.length?sections.sort((a,b)=>Number(a.order||0)-Number(b.order||0)).map(x=>`<article class="content-card"><h3>${esc(x.title)}</h3><small>${esc(pages.find(p=>p.id===x.pageId)?.name||'Page')}</small><p>${esc(x.text||'')}</p><div class="card-actions"><button data-se="${x.id}" class="action-btn edit">✏ Edit</button><button data-sd="${x.id}" class="action-btn delete">🗑 Delete</button></div></article>`).join(''):'<div class="empty-state">No sections.</div>'}
$('dpSave')?.addEventListener('click',saveP);$('dpClear')?.addEventListener('click',clearP);$('dsSave')?.addEventListener('click',saveS);$('dsClear')?.addEventListener('click',clearS);$('dpList')?.addEventListener('click',e=>{let b=e.target.closest('button');if(b?.dataset.pe)editP(b.dataset.pe);if(b?.dataset.pd)delP(b.dataset.pd)});$('dsList')?.addEventListener('click',e=>{let b=e.target.closest('button');if(b?.dataset.se)editS(b.dataset.se);if(b?.dataset.sd)delS(b.dataset.sd)});onSnapshot(collection(db,'dynamicPages'),s=>{pages=s.docs.map(d=>({id:d.id,...d.data()}));renderP();renderS()});onSnapshot(collection(db,'dynamicSections'),s=>{sections=s.docs.map(d=>({id:d.id,...d.data()}));renderS()});
