export const MASTER_CATALOG_VERSION = 8;

const commonDocs = ['Aadhaar Card / ID Proof','Passport Size Photo','Mobile Number'];
const addressDocs = [...commonDocs,'Address Proof'];
const bankDocs = [...commonDocs,'Bank Passbook'];

export const MASTER_SERVICES = [
  {id:'voter-id',name:'Voter ID',category:'Identity',icon:'🗳️',description:'Voter registration, correction, shifting, replacement and related assistance.',actions:[
    ['New Apply',100,'Available',['Aadhaar / ID Proof','Age Proof','Address Proof','Passport Size Photo'],'voter'],
    ['Correction / Update',100,'Available',['Existing Voter ID / EPIC','Aadhaar / ID Proof','Supporting Correction Proof','Passport Size Photo'],'voter'],
    ['Address Shift',100,'Available',['Existing Voter ID / EPIC','New Address Proof','Aadhaar / ID Proof'],'voter'],
    ['Replacement / Download Assistance',80,'Available',['EPIC Number / Existing Voter Details','Aadhaar / ID Proof'],'basic']
  ]},
  {id:'pan-card',name:'PAN Card',category:'Identity',icon:'💳',description:'PAN application, correction and e-PAN assistance.',actions:[
    ['New PAN Assistance',150,'Available',['Aadhaar Card','Passport Size Photo','Signature'],'pan'],
    ['PAN Correction',150,'Available',['Existing PAN Card','Aadhaar Card','Correction Proof','Photo / Signature if required'],'pan'],
    ['e-PAN / Status Assistance',80,'Available',['PAN / Acknowledgement Details','Aadhaar Card'],'basic']
  ]},
  {id:'eshram',name:'e-Shram Card',category:'Labour',icon:'👷',description:'e-Shram registration, update and download assistance.',actions:[
    ['Registration Assistance',80,'Available',bankDocs,'basic'],['Update Assistance',80,'Available',['e-Shram / UAN Details',...bankDocs],'basic'],['Download Assistance',50,'Available',['UAN / Registered Mobile'],'basic']
  ]},
  {id:'ayushman',name:'Ayushman Bharat Card',category:'Health',icon:'🏥',description:'Eligibility, registration and card download assistance.',actions:[
    ['Eligibility / Registration Assistance',100,'Available',['Aadhaar Card','Ration Card / Family ID if applicable','Mobile Number'],'basic'],['Card Download Assistance',50,'Available',['Aadhaar / Beneficiary Details','Registered Mobile'],'basic']
  ]},
  {id:'abha',name:'ABHA Card',category:'Health',icon:'🩺',description:'ABHA creation and download assistance.',actions:[['Create ABHA',50,'Available',['Aadhaar Card','Mobile Number'],'basic'],['Download ABHA',30,'Available',['ABHA Number / Mobile'],'basic']]},
  {id:'udid',name:'UDID Card',category:'Divyang',icon:'♿',description:'UDID application, update, status and download assistance.',actions:[
    ['New Apply',150,'Available',['Disability Certificate / Medical Documents','Aadhaar Card','Passport Size Photo','Signature','Address Proof'],'udid'],
    ['Update / Renewal Assistance',120,'Available',['Existing UDID / Enrollment Number','Supporting Documents','Aadhaar Card'],'udid'],
    ['Status / Download Assistance',50,'Available',['UDID / Enrollment Number'],'basic']
  ]},
  {id:'disability-certificate',name:'Disability Certificate',category:'Divyang',icon:'🧑‍⚕️',description:'Disability certificate application and status assistance.',actions:[['Application Assistance',150,'Available',['Aadhaar Card','Medical Records','Passport Size Photo','Address Proof'],'basic'],['Status Assistance',50,'Available',['Application / Enrollment Number'],'basic']]},
  {id:'maha-id',name:'Maha ID Card',category:'Maharashtra',icon:'🪪',description:'Maha ID registration, update and related assistance.',actions:[['Registration Assistance',100,'Available',['Aadhaar Card','Mobile Number','Passport Size Photo'],'basic'],['Update / Correction Assistance',100,'Available',['Existing Maha ID Details','Aadhaar Card','Correction Proof'],'basic'],['Status / Download Assistance',50,'Available',['Maha ID / Registration Details'],'basic']]},
  {id:'income-certificate',name:'Income Certificate',category:'Certificates',icon:'📄',description:'Income certificate online application assistance.',actions:[['New Apply',120,'Available',['Aadhaar Card','Ration Card','Income Proof / Self Declaration','Address Proof'],'certificate'],['Status Assistance',50,'Available',['Application ID'],'basic']]},
  {id:'caste-certificate',name:'Caste Certificate',category:'Certificates',icon:'📜',description:'Caste certificate application assistance.',actions:[['New Apply',150,'Available',['Aadhaar Card','Caste Supporting Documents','Family / School Records if applicable','Address Proof'],'certificate'],['Status Assistance',50,'Available',['Application ID'],'basic']]},
  {id:'ncl-certificate',name:'Non-Creamy Layer Certificate',category:'Certificates',icon:'📑',description:'NCL application and renewal assistance.',actions:[['New / Renewal Apply',150,'Available',['Aadhaar Card','Income Proof','Caste Certificate','Address Proof'],'certificate'],['Status Assistance',50,'Available',['Application ID'],'basic']]},
  {id:'domicile-certificate',name:'Domicile Certificate',category:'Certificates',icon:'🏠',description:'Domicile certificate application assistance.',actions:[['New Apply',150,'Available',['Aadhaar Card','Residence Proof','Birth / School Proof if applicable'],'certificate'],['Status Assistance',50,'Available',['Application ID'],'basic']]},
  {id:'nationality-certificate',name:'Nationality Certificate',category:'Certificates',icon:'🇮🇳',description:'Nationality certificate application assistance.',actions:[['New Apply',150,'Available',['Aadhaar Card','Birth Proof','Residence Proof'],'certificate']]},
  {id:'birth-certificate',name:'Birth Certificate',category:'Certificates',icon:'👶',description:'Birth certificate search, application and correction assistance.',actions:[['Application / Search Assistance',100,'Available',['Birth Details','Parents ID Proof','Hospital / Existing Record if available'],'birth'],['Correction Assistance',150,'Available',['Existing Birth Certificate','Correction Proof','Parents ID Proof'],'birth']]},
  {id:'death-certificate',name:'Death Certificate',category:'Certificates',icon:'🕯️',description:'Death certificate search, application and correction assistance.',actions:[['Application / Search Assistance',100,'Available',['Death Details','Applicant ID Proof','Hospital / Existing Record if available'],'death'],['Correction Assistance',150,'Available',['Existing Death Certificate','Correction Proof','Applicant ID Proof'],'death']]},
  {id:'marriage-certificate',name:'Marriage Certificate',category:'Certificates',icon:'💍',description:'Marriage registration assistance.',actions:[['Registration Assistance',200,'Available',['Bride & Groom Aadhaar','Passport Size Photos','Marriage Proof / Invitation / Photos','Witness Details','Address Proof'],'marriage']]},
  {id:'ration-card',name:'Ration Card',category:'Food & Civil Supplies',icon:'🍚',description:'Ration card new, correction and member changes assistance.',actions:[['New / Update Assistance',120,'Available',['Aadhaar of Family Members','Address Proof','Existing Ration Card if applicable'],'family'],['Member Add / Remove',120,'Available',['Existing Ration Card','Member Aadhaar','Relationship / Supporting Proof'],'family']]},
  {id:'ladki-bahin',name:'Ladki Bahin Yojana',category:'Maharashtra Yojana',icon:'👩',description:'Scheme application, update and status assistance.',actions:[['Application / Update Assistance',100,'Available',['Aadhaar Card','Bank Passbook','Residence / Eligibility Documents'],'scheme'],['Status Assistance',50,'Available',['Application / Aadhaar Details'],'basic']]},
  {id:'divyang-pension',name:'Divyang Pension',category:'Divyang',icon:'💰',description:'Divyang pension application and status assistance.',actions:[['Application Assistance',120,'Available',['UDID / Disability Certificate','Aadhaar Card','Bank Passbook','Residence Proof'],'scheme'],['Status Assistance',50,'Available',['Application ID / Beneficiary Details'],'basic']]},
  {id:'scholarship',name:'Scholarship',category:'Education',icon:'🎓',description:'Scholarship application, renewal and status assistance.',actions:[['New / Renewal Application',120,'Available',['Aadhaar Card','Marksheet','Income / Caste Certificate if applicable','Bank Passbook','Bonafide / Admission Proof'],'student'],['Status Assistance',50,'Available',['Application ID'],'basic']]},
  {id:'pm-kisan',name:'PM-Kisan',category:'Agriculture',icon:'🌾',description:'PM-Kisan registration, correction and eKYC assistance.',actions:[['Registration / Correction Assistance',100,'Available',['Aadhaar Card','Land Record','Bank Passbook'],'farmer'],['eKYC / Status Assistance',50,'Available',['Aadhaar Card','Registered Mobile'],'basic']]},
  {id:'agriculture-schemes',name:'Agriculture / Farmer Schemes',category:'Agriculture',icon:'🚜',description:'Agriculture scheme application and status assistance.',actions:[['Scheme Application Assistance',120,'Available',['Aadhaar Card','7/12 / Land Record if applicable','Bank Passbook','Scheme Specific Documents'],'farmer']]},
  {id:'labour-card',name:'Labour Card / Labour Schemes',category:'Labour',icon:'🦺',description:'Labour registration, renewal and scheme assistance.',actions:[['Registration / Renewal Assistance',120,'Available',['Aadhaar Card','Photo','Bank Passbook','Employment / Labour Proof if applicable'],'basic']]},
  {id:'passport',name:'Passport',category:'Travel & Identity',icon:'🛂',description:'Passport application and appointment assistance.',actions:[['Application / Appointment Assistance',200,'Available',['Aadhaar / ID Proof','DOB Proof','Address Proof','Passport Size Photo if required'],'passport'],['Status Assistance',50,'Available',['File / Application Number'],'basic']]},
  {id:'driving-licence',name:'Driving Licence',category:'RTO',icon:'🚗',description:'Learner, DL, renewal and correction assistance.',actions:[['Learner / New DL Assistance',150,'Available',['Aadhaar / ID Proof','Age Proof','Address Proof','Photo / Signature'],'rto'],['Renewal / Correction Assistance',150,'Available',['Existing Driving Licence','Aadhaar / ID Proof','Supporting Proof'],'rto']]},
  {id:'rc-services',name:'RC / Vehicle Services',category:'RTO',icon:'🚘',description:'RC transfer, update and related online assistance.',actions:[['RC Update / Transfer Assistance',200,'Available',['RC Copy','Owner ID Proof','Insurance / PUC if applicable','Supporting Documents'],'vehicle']]},
  {id:'fastag',name:'FASTag',category:'Vehicle',icon:'🛣️',description:'FASTag application and update assistance.',actions:[['Application / Update Assistance',100,'Available',['RC Copy','Owner Aadhaar / ID Proof','Mobile Number'],'vehicle']]},
  {id:'police-verification',name:'Police Verification',category:'Certificates',icon:'👮',description:'Police verification application assistance.',actions:[['Application Assistance',150,'Available',['Aadhaar / ID Proof','Address Proof','Purpose Documents'],'basic']]},
  {id:'character-certificate',name:'Character Certificate',category:'Certificates',icon:'✅',description:'Character certificate application assistance.',actions:[['Application Assistance',150,'Available',['Aadhaar / ID Proof','Address Proof','Purpose Documents'],'basic']]},
  {id:'udyam',name:'Udyam Registration',category:'Business',icon:'🏭',description:'MSME Udyam registration and update assistance.',actions:[['New Registration',150,'Available',['Aadhaar Card','PAN Card','Business Details','Bank Details'],'business'],['Update Assistance',100,'Available',['Udyam Number','Aadhaar / PAN','Updated Business Details'],'business']]},
  {id:'shop-act',name:'Shop Act / Gumasta',category:'Business',icon:'🏪',description:'Shop establishment registration and renewal assistance.',actions:[['Registration / Renewal Assistance',250,'Available',['Owner Aadhaar / PAN','Shop Address Proof','Business Details','Photo / Signature'],'business']]},
  {id:'fssai',name:'FSSAI Registration',category:'Business',icon:'🍽️',description:'Food business registration / renewal assistance.',actions:[['Registration / Renewal Assistance',250,'Available',['Owner ID / PAN','Business Address Proof','Food Business Details','Photo'],'business']]},
  {id:'gst',name:'GST Registration',category:'Business',icon:'🧾',description:'GST registration and update assistance.',actions:[['Registration Assistance',300,'Available',['PAN','Aadhaar','Business Address Proof','Bank Proof','Business Details'],'business'],['Update Assistance',200,'Available',['GSTIN','Updated Supporting Documents'],'business']]},
  {id:'jeevan-pramaan',name:'Digital Life Certificate / Jeevan Pramaan',category:'Pension',icon:'👴',description:'Digital life certificate assistance.',actions:[['Jeevan Pramaan Assistance',100,'Available',['Aadhaar Card','PPO / Pension Details','Bank Details'],'pension']]},
  {id:'pf-uan',name:'PF / UAN Services',category:'Employment',icon:'🏢',description:'UAN activation, eKYC and claim assistance.',actions:[['UAN / eKYC Assistance',100,'Available',['UAN','Aadhaar','PAN / Bank Details if applicable'],'employment'],['Claim Assistance',150,'Available',['UAN','Aadhaar','Bank Passbook / Cheque','Claim Details'],'employment']]},
  {id:'aadhaar-assistance',name:'Aadhaar Services Assistance',category:'Identity',icon:'🪪',description:'Authorized Aadhaar appointment / update guidance and assistance only.',actions:[['Appointment / Update Guidance',80,'Available',['Aadhaar Card','Supporting Update Proof'],'basic']]},
  {id:'electricity',name:'Electricity Online Services',category:'Utility',icon:'⚡',description:'Electricity bill and consumer online assistance.',actions:[['Bill / Consumer Service Assistance',50,'Available',['Consumer Number / Bill Copy','Mobile Number'],'utility']]},
  {id:'exam-forms',name:'Government Exam Forms',category:'Education',icon:'📝',description:'Government recruitment / exam online form assistance.',actions:[['Online Application Assistance',120,'Available',['Aadhaar / ID Proof','Photo','Signature','Education Documents'],'student']]},
  {id:'admission-forms',name:'College / Admission Forms',category:'Education',icon:'🏫',description:'College and admission online form assistance.',actions:[['Online Application Assistance',120,'Available',['Aadhaar / ID Proof','Photo','Marksheet / Education Documents'],'student']]},
  {id:'passport-photo',name:'Passport Size Photo',category:'Photo & Print',icon:'📸',description:'Passport size photo preparation and print assistance.',actions:[['Passport Photo Preparation',50,'Available',['Clear Recent Photo / Camera Photo'],'photo']]},
  {id:'other-govt-schemes',name:'Other Government Schemes',category:'Government Schemes',icon:'🏛️',description:'Other government scheme application assistance configured by Admin.',actions:[['Application Assistance',100,'Coming Soon',['Aadhaar Card','Scheme Specific Documents'],'scheme']]}
];

const PRESETS={
 basic:[['Full Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Email','email',false,'email'],['Date of Birth','date',false,'dob'],['Full Address','textarea',false,'address']],
 voter:[['Full Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Date of Birth','date',true,'dob'],['Gender','select',false,'gender',['Male','Female','Other']],['EPIC Number (if existing)','text',false,''],['Full Address','textarea',true,'address'],['District','text',false,'district'],['State','text',false,'state'],['PIN Code','text',false,'pinCode'],['Correction / Request Details','textarea',false,'']],
 pan:[['Full Name as per Aadhaar','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Email','email',false,'email'],['Date of Birth','date',true,'dob'],['Existing PAN Number (if correction)','text',false,''],['Father Name','text',false,''],['Full Address','textarea',true,'address']],
 udid:[['Full Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Date of Birth','date',true,'dob'],['Gender','select',false,'gender',['Male','Female','Other']],['UDID / Enrollment No. (if existing)','text',false,''],['Disability Type / Details','textarea',false,''],['Full Address','textarea',true,'address'],['District','text',false,'district']],
 certificate:[['Full Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Date of Birth','date',false,'dob'],['Full Address','textarea',true,'address'],['Village / City','text',false,'villageCity'],['Taluka','text',false,'taluka'],['District','text',false,'district'],['Purpose','textarea',false,'']],
 birth:[['Applicant Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Person Name on Record','text',true,''],['Date of Birth','date',true,''],['Place of Birth','text',false,''],['Father Name','text',false,''],['Mother Name','text',false,''],['Request / Correction Details','textarea',false,'']],
 death:[['Applicant Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Deceased Person Name','text',true,''],['Date of Death','date',true,''],['Place of Death','text',false,''],['Request / Correction Details','textarea',false,'']],
 marriage:[['Applicant Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Bride Name','text',true,''],['Groom Name','text',true,''],['Marriage Date','date',true,''],['Marriage Place','text',false,''],['Full Address','textarea',true,'address']],
 family:[['Applicant Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Ration Card Number (if existing)','text',false,''],['Family / Member Request Details','textarea',true,''],['Full Address','textarea',true,'address']],
 scheme:[['Full Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Date of Birth','date',false,'dob'],['Aadhaar Last 4 Digits','text',false,''],['Bank Account Last 4 Digits','text',false,''],['Full Address','textarea',true,'address'],['Scheme / Request Details','textarea',false,'']],
 student:[['Student Full Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Email','email',false,'email'],['Date of Birth','date',true,'dob'],['Course / Exam / Admission Name','text',true,''],['Qualification / Class','text',false,''],['Category','text',false,''],['Full Address','textarea',false,'address']],
 farmer:[['Farmer Full Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Aadhaar Last 4 Digits','text',false,''],['Village / City','text',false,'villageCity'],['Taluka','text',false,'taluka'],['District','text',false,'district'],['Land / Scheme Details','textarea',false,'']],
 passport:[['Full Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Email','email',false,'email'],['Date of Birth','date',true,'dob'],['Place of Birth','text',false,''],['Full Address','textarea',true,'address'],['Passport Number (if existing)','text',false,'']],
 rto:[['Full Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Date of Birth','date',true,'dob'],['Existing DL / LL Number','text',false,''],['Vehicle Class / Request','text',false,''],['Full Address','textarea',true,'address']],
 vehicle:[['Owner Full Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Vehicle Registration Number','text',true,''],['Chassis Last 5 Digits','text',false,''],['Request Details','textarea',false,''],['Full Address','textarea',false,'address']],
 business:[['Applicant / Proprietor Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Email','email',false,'email'],['Business Name','text',true,''],['Business Type','text',false,''],['Business Address','textarea',true,'address'],['PAN / Registration Details','text',false,'']],
 pension:[['Pensioner Full Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['PPO / Pension Number','text',false,''],['Aadhaar Last 4 Digits','text',false,''],['Bank / Branch','text',false,'']],
 employment:[['Full Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['UAN / Employee ID','text',false,''],['Request Details','textarea',false,'']],
 utility:[['Customer Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Consumer Number','text',true,''],['Request Details','textarea',false,'']],
 photo:[['Customer Name','text',true,'fullName'],['Mobile Number','tel',true,'mobile'],['Photo Quantity','number',false,''],['Background Preference','select',false,'',['White','Light Blue','Other']],['Special Instructions','textarea',false,'']]
};

export function actionId(serviceId,name){return `act_${serviceId}_${String(name).toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,48)}`}
export function fieldsFor(action){const preset=PRESETS[action[4]]||PRESETS.basic;return preset.map((x,i)=>({label:x[0],type:x[1],required:x[2],profileKey:x[3]||'',options:x[4]||[],order:(i+1)*10}))}
