import {db} from './supabase-app.js';
import {collection,onSnapshot,doc,getDoc,setDoc,serverTimestamp,deleteDoc} from './supabase-db.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const date=v=>{try{return (v?.toDate?v.toDate():new Date(v)).toLocaleString('en-IN')}catch{return'—'}};
let rows=[];
function render(data=rows){const tb=$('paymentsTable');if(!tb)return;rows=[...data];const sorted=[...rows].sort((a,b)=>((b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)));tb.innerHTML=sorted.length?sorted.map(x=>`<tr><td>${esc(x.paymentId||x.id)}</td><td>${esc(x.applicationId||'—')}</td><td>₹${Number(x.amount||0).toLocaleString('en-IN')}</td><td><span class="status-pill ${String(x.status||'pending').toLowerCase()}">${esc(x.status||'Pending')}</span></td><td>${esc(x.transactionReference||x.reference||'—')}</td><td>${date(x.createdAt||x.paymentDate)}</td><td><button class="action-btn danger" data-delete-payment="${esc(x.id)}">Delete</button></td></tr>`).join(''):'<tr><td colspan="7">No payment records.</td></tr>';const paid=rows.filter(x=>x.status==='Paid'||x.status==='Success');$('paymentTotalCollection')&&($('paymentTotalCollection').textContent='₹'+paid.reduce((s,x)=>s+Number(x.amount||0),0).toLocaleString('en-IN'));$('paymentSuccessCount')&&($('paymentSuccessCount').textContent=paid.length);$('paymentPendingCount')&&($('paymentPendingCount').textContent=rows.filter(x=>x.status==='Pending').length);$('paymentFailedCount')&&($('paymentFailedCount').textContent=rows.filter(x=>x.status==='Failed').length)}
onSnapshot(collection(db,'payments'),s=>render(s.docs.map(d=>({id:d.id,...d.data()}))));
$('paymentsTable')?.addEventListener('click',async e=>{const b=e.target.closest('[data-delete-payment]');if(!b)return;const item=rows.find(x=>x.id===b.dataset.deletePayment);if(!item)return;const ref=item.paymentId||item.transactionReference||item.id;if(!confirm(`Delete transaction ${ref}?\n\nThis will permanently remove this transaction record from Admin > Payments / PayU.`))return;b.disabled=true;const oldText=b.textContent;b.textContent='Deleting...';try{await deleteDoc(doc(db,'payments',item.id));}catch(err){console.error(err);alert('Transaction delete failed. Please check admin access and try again.');b.disabled=false;b.textContent=oldText;}});
async function load(){const s=await getDoc(doc(db,'settings','payu'));if(!s.exists())return;const x=s.data();$('payuEnvironment').value=x.environment||'test';$('payuMerchantKey').value=x.merchantKey||'';$('payuBackendUrl').value=x.backendUrl||'';$('payuSuccessUrl').value=x.successUrl||'';$('payuFailureUrl').value=x.failureUrl||'';$('payuPortalReturnUrl').value=x.portalReturnUrl||''}
$('savePayuSettings')?.addEventListener('click',async()=>{await setDoc(doc(db,'settings','payu'),{environment:$('payuEnvironment').value,merchantKey:$('payuMerchantKey').value.trim(),backendUrl:$('payuBackendUrl').value.trim(),successUrl:$('payuSuccessUrl').value.trim(),failureUrl:$('payuFailureUrl').value.trim(),portalReturnUrl:$('payuPortalReturnUrl').value.trim(),updatedAt:serverTimestamp()},{merge:true});$('payuMessage').textContent='PayU public settings saved. Merchant Salt/Secret backend me hi rakhein.'});load();
