import {db} from './supabase-app.js';
import {collection,onSnapshot,doc,deleteDoc} from './supabase-db.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const date=v=>{try{return (v?.toDate?v.toDate():new Date(v)).toLocaleString('en-IN')}catch{return'—'}};
let rows=[];
function render(data=rows){const tb=$('paymentsTable');if(!tb)return;rows=[...data];const sorted=[...rows].sort((a,b)=>((b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)));tb.innerHTML=sorted.length?sorted.map(x=>`<tr><td>${esc(x.paymentId||x.id)}</td><td>${esc(x.applicationId||'—')}</td><td>₹${Number(x.amount||0).toLocaleString('en-IN')}</td><td><span class="status-pill ${String(x.status||'pending').toLowerCase()}">${esc(x.status||'Pending')}</span></td><td>${esc(x.transactionReference||x.reference||'—')}</td><td>${date(x.createdAt||x.paymentDate)}</td><td><button class="action-btn danger" data-delete-payment="${esc(x.id)}">Delete</button></td></tr>`).join(''):'<tr><td colspan="7">No payment records.</td></tr>';const paid=rows.filter(x=>x.status==='Paid'||x.status==='Success');$('paymentTotalCollection')&&($('paymentTotalCollection').textContent='₹'+paid.reduce((s,x)=>s+Number(x.amount||0),0).toLocaleString('en-IN'));$('paymentSuccessCount')&&($('paymentSuccessCount').textContent=paid.length);$('paymentPendingCount')&&($('paymentPendingCount').textContent=rows.filter(x=>x.status==='Pending').length);$('paymentFailedCount')&&($('paymentFailedCount').textContent=rows.filter(x=>x.status==='Failed').length)}
onSnapshot(collection(db,'payments'),s=>render(s.docs.map(d=>({id:d.id,...d.data()}))));
$('paymentsTable')?.addEventListener('click',async e=>{const b=e.target.closest('[data-delete-payment]');if(!b)return;const item=rows.find(x=>x.id===b.dataset.deletePayment);if(!item)return;const ref=item.paymentId||item.transactionReference||item.id;if(!confirm(`Delete transaction ${ref}?\n\nThis will permanently remove this transaction record from Admin > Payments / PayU.`))return;
const oldRows=[...rows];rows=rows.filter(x=>x.id!==item.id);render(rows);
try{await deleteDoc(doc(db,'payments',item.id))}
catch(err){console.error(err);rows=oldRows;render(rows);alert('Transaction delete failed. Please check admin access and try again.')}});
