import {db} from './firebase-config.js';
import {collection,getDocs,onSnapshot,addDoc,updateDoc,deleteDoc,doc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let services=[],actions=[],fields=[],editAction=null,editField=null;
function serviceName(id){return services.find(s=>s.id===id)?.name||'Unknown Service'}
function fillServices(){const opts=services.map(s=>`<option value="${s.id}">${esc(s.name||s.title||s.id)}</option>`).join('');if($('actionService'))$('actionService').innerHTML=opts;if($('actionServiceFilter'))$('actionServiceFilter').innerHTML='<option value="all">All Services</option>'+opts;if($('chargeServiceFilter'))$('chargeServiceFilter').innerHTML='<option value="all">All Services</option>'+opts}
function fillActions(){const opts=actions.map(a=>`<option value="${a.id}">${esc(serviceName(a.serviceId)+' → '+a.name)}</option>`).join('');if($('fieldAction'))$('fieldAction').innerHTML=opts}
function renderActions(){const f=$('actionServiceFilter')?.value||'all',box=$('serviceActionsList');if(!box)return;const a=actions.filter(x=>f==='all'||x.serviceId===f).sort((x,y)=>(x.order||0)-(y.order||0));box.innerHTML=a.length?a.map(x=>`<article class="content-card"><h3>${esc(x.name)}</h3><p>${esc(serviceName(x.serviceId))}</p><p><b>Service Charge:</b> ₹${Number(x.serviceCharge||0)} &nbsp; <b>Official Fee:</b> ₹${Number(x.officialFee||0)}</p><p><b>${esc(x.availabilityStatus||((x.available!==false)?'Available':'Unavailable'))}</b> • Order ${x.order||0}</p><div class="card-actions"><button class="action-btn edit" data-ae="${x.id}">Edit / Update</button><button class="action-btn delete" data-ad="${x.id}">Delete Action</button></div></article>`).join(''):'<div class="empty-state">No service actions.</div>'}
function renderCharges(){const body=$('serviceChargesTable');if(!body)return;const filter=$('chargeServiceFilter')?.value||'all',q=($('chargeSearch')?.value||'').trim().toLowerCase();const rows=actions.filter(a=>(filter==='all'||a.serviceId===filter)&&(!q||(`${serviceName(a.serviceId)} ${a.name||''}`).toLowerCase().includes(q))).sort((a,b)=>serviceName(a.serviceId).localeCompare(serviceName(b.serviceId))||Number(a.order||0)-Number(b.order||0));body.innerHTML=rows.length?rows.map(a=>`<tr><td><b>${esc(serviceName(a.serviceId))}</b></td><td>${esc(a.name||'Action')}</td><td><input class="charge-inline-input" data-charge-input="${a.id}" type="number" min="0" value="${Number(a.serviceCharge||0)}" style="width:110px"></td><td><select data-charge-status="${a.id}"><option ${((a.availabilityStatus||'Available')==='Available')?'selected':''}>Available</option><option ${a.availabilityStatus==='Unavailable'?'selected':''}>Unavailable</option><option ${a.availabilityStatus==='Coming Soon'?'selected':''}>Coming Soon</option></select></td><td><div class="card-actions compact"><button class="action-btn edit" data-charge-update="${a.id}">Update Charge</button><button class="action-btn delete" data-charge-delete="${a.id}">Delete Charge</button></div></td></tr>`).join(''):'<tr><td colspan="5">No matching service charges.</td></tr>'}
function renderFields(){const id=$('fieldAction')?.value,box=$('formFieldsList');if(!box)return;const a=fields.filter(x=>x.actionId===id).sort((x,y)=>(x.order||0)-(y.order||0));box.innerHTML=a.length?a.map(x=>`<article class="content-card"><h3>${esc(x.label)}</h3><p>${esc(x.type)} • ${x.required?'Required':'Optional'} • Order ${x.order||0}</p><div class="card-actions"><button class="action-btn edit" data-fe="${x.id}">Edit</button><button class="action-btn delete" data-fd="${x.id}">Delete</button></div></article>`).join(''):'<div class="empty-state">No fields for this action.</div>'}
function clearA(){editAction=null;if($('actionName'))$('actionName').value='';if($('actionCharge'))$('actionCharge').value=0;if($('actionOfficialFee'))$('actionOfficialFee').value=0;if($('actionDescription'))$('actionDescription').value='';if($('actionDocuments'))$('actionDocuments').value='';if($('actionAvailable'))$('actionAvailable').value='Available';if($('actionOrder'))$('actionOrder').value=1;if($('saveServiceAction'))$('saveServiceAction').textContent='Save Action'}
function clearF(){editField=null;if($('fieldLabel'))$('fieldLabel').value='';if($('fieldType'))$('fieldType').value='text';if($('fieldOptions'))$('fieldOptions').value='';if($('fieldRequired'))$('fieldRequired').value='true';if($('fieldOrder'))$('fieldOrder').value=1}
async function init(){const s=await getDocs(collection(db,'services'));services=s.docs.map(d=>({id:d.id,...d.data()}));fillServices();onSnapshot(collection(db,'serviceActions'),q=>{actions=q.docs.map(d=>({id:d.id,...d.data()}));fillActions();renderActions();renderCharges();renderFields()});onSnapshot(collection(db,'formFields'),q=>{fields=q.docs.map(d=>({id:d.id,...d.data()}));renderFields()})}
$('saveServiceAction')?.addEventListener('click',async()=>{const data={serviceId:$('actionService').value,name:$('actionName').value.trim(),serviceCharge:Number($('actionCharge').value||0),officialFee:Number($('actionOfficialFee').value||0),description:$('actionDescription').value.trim(),requiredDocuments:$('actionDocuments').value.split('\n').map(x=>x.trim()).filter(Boolean),availabilityStatus:$('actionAvailable').value,available:$('actionAvailable').value==='Available',order:Number($('actionOrder').value||0),updatedAt:serverTimestamp()};if(!data.serviceId||!data.name)return alert('Service aur Action Name required.');if(editAction)await updateDoc(doc(db,'serviceActions',editAction),data);else await addDoc(collection(db,'serviceActions'),{...data,createdAt:serverTimestamp()});clearA()});
$('serviceActionsList')?.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.ae){const x=actions.find(a=>a.id===b.dataset.ae);editAction=x.id;$('actionService').value=x.serviceId;$('actionName').value=x.name||'';$('actionCharge').value=x.serviceCharge||0;$('actionOfficialFee').value=x.officialFee||0;$('actionDescription').value=x.description||'';$('actionDocuments').value=(x.requiredDocuments||[]).join('\n');$('actionAvailable').value=x.availabilityStatus||((x.available!==false)?'Available':'Unavailable');$('actionOrder').value=x.order||1;$('saveServiceAction').textContent='Update Action';$('portalbuilderPage')?.scrollIntoView({behavior:'smooth',block:'start'})}else if(b.dataset.ad&&confirm('Action delete karein?'))await deleteDoc(doc(db,'serviceActions',b.dataset.ad))});
$('serviceChargesTable')?.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.chargeUpdate||b.dataset.chargeDelete;if(!id)return;const ref=doc(db,'serviceActions',id);if(b.dataset.chargeDelete){if(!confirm('Is action ka service charge ₹0 karna hai? Action delete nahi hoga.'))return;await updateDoc(ref,{serviceCharge:0,updatedAt:serverTimestamp()});return}const input=document.querySelector(`[data-charge-input="${id}"]`),status=document.querySelector(`[data-charge-status="${id}"]`);await updateDoc(ref,{serviceCharge:Number(input?.value||0),availabilityStatus:status?.value||'Available',available:(status?.value||'Available')==='Available',updatedAt:serverTimestamp()});alert('Service charge updated successfully.')});
$('chargeServiceFilter')?.addEventListener('change',renderCharges);$('chargeSearch')?.addEventListener('input',renderCharges);$('actionServiceFilter')?.addEventListener('change',renderActions);$('clearServiceAction')?.addEventListener('click',clearA);$('fieldAction')?.addEventListener('change',renderFields);
$('saveFormField')?.addEventListener('click',async()=>{const data={actionId:$('fieldAction').value,label:$('fieldLabel').value.trim(),type:$('fieldType').value,options:$('fieldOptions').value.split(',').map(x=>x.trim()).filter(Boolean),required:$('fieldRequired').value==='true',order:Number($('fieldOrder').value||0),updatedAt:serverTimestamp()};if(!data.actionId||!data.label)return alert('Action aur Field Label required.');if(editField)await updateDoc(doc(db,'formFields',editField),data);else await addDoc(collection(db,'formFields'),{...data,createdAt:serverTimestamp()});clearF()});
$('formFieldsList')?.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.fe){const x=fields.find(a=>a.id===b.dataset.fe);editField=x.id;$('fieldAction').value=x.actionId;$('fieldLabel').value=x.label||'';$('fieldType').value=x.type||'text';$('fieldOptions').value=(x.options||[]).join(', ');$('fieldRequired').value=String(x.required!==false);$('fieldOrder').value=x.order||1}else if(b.dataset.fd&&confirm('Field delete karein?'))await deleteDoc(doc(db,'formFields',b.dataset.fd))});
$('clearFormField')?.addEventListener('click',clearF);init();
