import {db} from './supabase-app.js';
import {collection,getDocs,onSnapshot,addDoc,updateDoc,deleteDoc,doc,setDoc,serverTimestamp,writeBatch} from './supabase-db.js';
import {MASTER_SERVICES,MASTER_CATALOG_VERSION,actionId,fieldsFor} from './master-catalog.js?v=20260824-supabasefinal1';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let services=[],actions=[],fields=[],editAction=null,editField=null,editServiceId=null;
function renderBuilderServices(){const box=$('builderServicesList');if(!box)return;const q=($('builderServiceSearch')?.value||'').trim().toLowerCase();const rows=services.filter(x=>!q||(`${x.name||''} ${x.category||''} ${x.description||''}`).toLowerCase().includes(q)).sort((a,b)=>(a.name||'').localeCompare(b.name||''));box.innerHTML=rows.length?rows.map(x=>`<article class="content-card"><div class="content-card-head"><span class="service-icon">${esc(x.icon||'🧰')}</span><span class="status-badge">${esc(x.status||'Published')}</span></div><h3>${esc(x.name||'Service')}</h3><p>${esc(x.description||'')}</p><small>${esc(x.category||'Government')} • ${esc(x.availabilityStatus||'Available')}</small><div class="card-actions"><button class="action-btn edit" data-se="${x.id}">Edit / Update</button><button class="action-btn delete" data-sd="${x.id}">Delete Service + Forms</button></div></article>`).join(''):'<div class="empty-state">No matching services.</div>'}
function clearBuilderService(){editServiceId=null;for(const id of ['builderServiceName','builderServiceDescription','builderServiceCategory','builderServiceIcon'])if($(id))$(id).value=id==='builderServiceCategory'?'Government':'';if($('builderServiceStatus'))$('builderServiceStatus').value='Published';if($('builderServiceAvailability'))$('builderServiceAvailability').value='Available';if($('builderServiceTarget'))$('builderServiceTarget').value='_self';if($('saveBuilderService'))$('saveBuilderService').textContent='Add Service'}
async function saveBuilderService(){const data={name:$('builderServiceName')?.value.trim()||'',description:$('builderServiceDescription')?.value.trim()||'',category:$('builderServiceCategory')?.value.trim()||'Government',icon:$('builderServiceIcon')?.value.trim()||'🧰',status:$('builderServiceStatus')?.value||'Published',availabilityStatus:$('builderServiceAvailability')?.value||'Available',target:$('builderServiceTarget')?.value||'_self',updatedAt:serverTimestamp()};if(!data.name)return alert('Service Name required.');const dup=services.find(x=>x.id!==editServiceId&&String(x.name||'').trim().toLowerCase()===data.name.toLowerCase());if(dup)return alert('Duplicate service name not allowed.');if(editServiceId)await updateDoc(doc(db,'services',editServiceId),data);else await addDoc(collection(db,'services'),{...data,createdAt:serverTimestamp()});clearBuilderService()}
async function deleteBuilderService(id){const svc=services.find(x=>x.id===id);if(!svc||!confirm(`Delete "${svc.name}" and its actions/form fields? This cannot be undone.`))return;const actSnap=await getDocs(collection(db,'serviceActions'));const related=actSnap.docs.filter(d=>d.data().serviceId===id);const actionIds=new Set(related.map(d=>d.id));const fldSnap=await getDocs(collection(db,'formFields'));const batch=writeBatch(db);fldSnap.docs.forEach(d=>{if(actionIds.has(d.data().actionId))batch.delete(d.ref)});related.forEach(d=>batch.delete(d.ref));batch.delete(doc(db,'services',id));await batch.commit();clearBuilderService()}
function serviceName(id){return services.find(s=>s.id===id)?.name||'Unknown Service'}
function fillServices(){const opts=services.map(s=>`<option value="${s.id}">${esc(s.name||s.title||s.id)}</option>`).join('');if($('actionService'))$('actionService').innerHTML=opts;if($('actionServiceFilter'))$('actionServiceFilter').innerHTML='<option value="all">All Services</option>'+opts;if($('chargeServiceFilter'))$('chargeServiceFilter').innerHTML='<option value="all">All Services</option>'+opts;const cats=[...new Set(services.map(s=>String(s.category||'').trim()).filter(Boolean))].sort();if($('serviceCategoryOptions'))$('serviceCategoryOptions').innerHTML=cats.map(c=>`<option value="${esc(c)}"></option>`).join('')}
function fillActions(){const opts=actions.map(a=>`<option value="${a.id}">${esc(serviceName(a.serviceId)+' → '+a.name)}</option>`).join('');if($('fieldAction'))$('fieldAction').innerHTML=opts}
function renderActions(){const f=$('actionServiceFilter')?.value||'all',box=$('serviceActionsList');if(!box)return;const a=actions.filter(x=>f==='all'||x.serviceId===f).sort((x,y)=>(x.order||0)-(y.order||0));box.innerHTML=a.length?a.map(x=>`<article class="content-card"><h3>${esc(x.name)}</h3><p>${esc(serviceName(x.serviceId))}</p><p><b>Service Charge:</b> ₹${Number(x.serviceCharge||0)} &nbsp; <b>Official Fee:</b> ₹${Number(x.officialFee||0)}</p><p><b>${esc(x.availabilityStatus||((x.available!==false)?'Available':'Unavailable'))}</b> • Order ${x.order||0}</p><div class="card-actions"><button class="action-btn edit" data-ae="${x.id}">Edit / Update</button><button class="action-btn delete" data-ad="${x.id}">Delete Action</button></div></article>`).join(''):'<div class="empty-state">No service actions.</div>'}
function renderCharges(){const body=$('serviceChargesTable');if(!body)return;const filter=$('chargeServiceFilter')?.value||'all',q=($('chargeSearch')?.value||'').trim().toLowerCase();const rows=actions.filter(a=>(filter==='all'||a.serviceId===filter)&&(!q||(`${serviceName(a.serviceId)} ${a.name||''}`).toLowerCase().includes(q))).sort((a,b)=>serviceName(a.serviceId).localeCompare(serviceName(b.serviceId))||Number(a.order||0)-Number(b.order||0));body.innerHTML=rows.length?rows.map(a=>`<tr><td><b>${esc(serviceName(a.serviceId))}</b></td><td>${esc(a.name||'Action')}</td><td><input class="charge-inline-input" data-charge-input="${a.id}" type="number" min="0" value="${Number(a.serviceCharge||0)}" style="width:110px"></td><td><select data-charge-status="${a.id}"><option ${((a.availabilityStatus||'Available')==='Available')?'selected':''}>Available</option><option ${a.availabilityStatus==='Unavailable'?'selected':''}>Unavailable</option><option ${a.availabilityStatus==='Coming Soon'?'selected':''}>Coming Soon</option></select></td><td><div class="card-actions compact"><button class="action-btn edit" data-charge-update="${a.id}">Update Charge</button><button class="action-btn delete" data-charge-delete="${a.id}">Delete Charge</button></div></td></tr>`).join(''):'<tr><td colspan="5">No matching service charges.</td></tr>'}
function renderFields(){const id=$('fieldAction')?.value,box=$('formFieldsList');if(!box)return;const a=fields.filter(x=>x.actionId===id).sort((x,y)=>(x.order||0)-(y.order||0));box.innerHTML=a.length?a.map(x=>`<article class="content-card"><h3>${esc(x.label)}</h3><p>${esc(x.type)} • ${x.required?'Required':'Optional'} • Order ${x.order||0}</p><div class="card-actions"><button class="action-btn edit" data-fe="${x.id}">Edit</button><button class="action-btn delete" data-fd="${x.id}">Delete</button></div></article>`).join(''):'<div class="empty-state">No fields for this action.</div>'}
function renderExistingForms(){
 const box=$('existingFormsList');if(!box)return;
 const q=($('existingFormSearch')?.value||'').trim().toLowerCase();
 const rows=actions.filter(a=>{const text=`${serviceName(a.serviceId)} ${a.name||''}`.toLowerCase();return !q||text.includes(q)}).sort((a,b)=>serviceName(a.serviceId).localeCompare(serviceName(b.serviceId))||Number(a.order||0)-Number(b.order||0));
 box.innerHTML=rows.length?rows.map(a=>{const ff=fields.filter(f=>f.actionId===a.id).sort((x,y)=>Number(x.order||0)-Number(y.order||0));const docs=a.requiredDocuments||[];return `<article class="content-card"><div class="content-card-head"><span class="service-icon">🧾</span><span class="status-badge">${ff.length} Fields</span></div><h3>${esc(a.name||'Form')}</h3><p><b>${esc(serviceName(a.serviceId))}</b></p><p>${ff.length?ff.slice(0,5).map(f=>esc(f.label)).join(' • '):'<em>No fields yet</em>'}${ff.length>5?' • +'+(ff.length-5)+' more':''}</p><p><b>Documents:</b> ${docs.length?docs.map(esc).join(', '):'None'}</p><div class="card-actions"><button class="action-btn edit" data-form-edit="${a.id}">Edit / Update Form</button><button class="action-btn delete" data-form-delete="${a.id}">Delete Form</button></div></article>`}).join(''):'<div class="empty-state">No existing forms found.</div>';
}
function openExistingForm(actionId){
 if($('fieldAction')){$('fieldAction').value=actionId;renderFields()}
 if($('v30DocsAction')){$('v30DocsAction').value=actionId;$('v30DocsAction').dispatchEvent(new Event('change'))}
 const target=$('formsmanagerMount')?.querySelector('.portal-form-builder')||$('fieldAction');target?.scrollIntoView({behavior:'smooth',block:'start'});
}
async function deleteExistingForm(actionId){
 const a=actions.find(x=>x.id===actionId);if(!a)return;
 if(!confirm(`Delete form for "${serviceName(a.serviceId)} → ${a.name||'Action'}"?\n\nAll form fields and required document requirements will be deleted. Service and Action will NOT be deleted.`))return;
 const related=fields.filter(f=>f.actionId===actionId);const batch=writeBatch(db);related.forEach(f=>batch.delete(doc(db,'formFields',f.id)));batch.update(doc(db,'serviceActions',actionId),{requiredDocuments:[],updatedAt:serverTimestamp()});await batch.commit();
 alert('Form deleted. Service and Action are still safe.');
}

function renderAtoZ(){const body=$('serviceAtoZTable');if(!body)return;const q=($('azSearch')?.value||'').trim().toLowerCase();const rows=[];for(const svc of [...services].sort((a,b)=>(a.name||'').localeCompare(b.name||''))){const aa=actions.filter(a=>a.serviceId===svc.id).sort((a,b)=>Number(a.order||0)-Number(b.order||0));if(!aa.length)rows.push({svc,action:null});else aa.forEach(action=>rows.push({svc,action}))}const filtered=rows.filter(({svc,action})=>!q||`${svc.name||''} ${svc.category||''} ${action?.name||''}`.toLowerCase().includes(q));body.innerHTML=filtered.length?filtered.map(({svc,action})=>`<tr><td><b>${esc(svc.name||'Service')}</b><br><small>${esc(svc.status||'Published')}</small></td><td>${esc(svc.category||'Government')}</td><td>${action?esc(action.name||'Action'):'<em>No action yet</em>'}</td><td>${action?`<input type="number" min="0" value="${Number(action.serviceCharge||0)}" data-az-charge="${action.id}" style="width:95px">`:'—'}</td><td>${action?`<select data-az-status="${action.id}"><option ${((action.availabilityStatus||'Available')==='Available')?'selected':''}>Available</option><option ${action.availabilityStatus==='Unavailable'?'selected':''}>Unavailable</option><option ${action.availabilityStatus==='Coming Soon'?'selected':''}>Coming Soon</option></select>`:esc(svc.availabilityStatus||'Available')}</td><td><div class="card-actions compact"><button class="action-btn edit" data-az-se="${svc.id}">Edit Service</button><button class="action-btn delete" data-az-sd="${svc.id}">Delete Service</button>${action?`<button class="action-btn edit" data-az-ae="${action.id}">Edit Action</button><button class="action-btn edit" data-az-save="${action.id}">Update Charge</button><button class="action-btn delete" data-az-zero="${action.id}">Charge ₹0</button><button class="action-btn delete" data-az-ad="${action.id}">Delete Action</button>`:''}</div></td></tr>`).join(''):'<tr><td colspan="6">No matching service/action.</td></tr>'}
function clearA(){editAction=null;if($('actionName'))$('actionName').value='';if($('actionCharge'))$('actionCharge').value=0;if($('actionOfficialFee'))$('actionOfficialFee').value=0;if($('actionDescription'))$('actionDescription').value='';if($('actionDocuments'))$('actionDocuments').value='';if($('actionAvailable'))$('actionAvailable').value='Available';if($('actionOrder'))$('actionOrder').value=1;if($('saveServiceAction'))$('saveServiceAction').textContent='Save Action'}
function clearF(){editField=null;if($('fieldLabel'))$('fieldLabel').value='';if($('fieldType'))$('fieldType').value='text';if($('fieldOptions'))$('fieldOptions').value='';if($('fieldRequired'))$('fieldRequired').value='true';if($('fieldOrder'))$('fieldOrder').value=1;if($('fieldProfileKey'))$('fieldProfileKey').value=''}
async function init(){onSnapshot(collection(db,'services'),q=>{services=q.docs.map(d=>({id:d.id,...d.data()}));fillServices();renderBuilderServices();renderActions();renderCharges();renderAtoZ()});onSnapshot(collection(db,'serviceActions'),q=>{actions=q.docs.map(d=>({id:d.id,...d.data()}));fillActions();renderActions();renderCharges();renderFields();renderExistingForms();renderAtoZ()});onSnapshot(collection(db,'formFields'),q=>{fields=q.docs.map(d=>({id:d.id,...d.data()}));renderFields();renderExistingForms()})}
$('saveBuilderService')?.addEventListener('click',()=>saveBuilderService().catch(e=>alert(e.message)));
$('clearBuilderService')?.addEventListener('click',clearBuilderService);
$('builderServiceSearch')?.addEventListener('input',renderBuilderServices);
$('builderServicesList')?.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.se){const x=services.find(s=>s.id===b.dataset.se);if(!x)return;editServiceId=x.id;$('builderServiceName').value=x.name||'';$('builderServiceDescription').value=x.description||'';$('builderServiceCategory').value=x.category||'Government';$('builderServiceIcon').value=x.icon||'';$('builderServiceStatus').value=x.status||'Published';$('builderServiceAvailability').value=x.availabilityStatus||'Available';if($('builderServiceTarget'))$('builderServiceTarget').value=x.target||'_self';$('saveBuilderService').textContent='Update Service';$('portalbuilderPage')?.scrollIntoView({behavior:'smooth',block:'start'})}else if(b.dataset.sd)deleteBuilderService(b.dataset.sd).catch(err=>alert(err.message))});

$('saveServiceAction')?.addEventListener('click',async()=>{const data={serviceId:$('actionService').value,name:$('actionName').value.trim(),serviceCharge:Number($('actionCharge').value||0),officialFee:Number($('actionOfficialFee').value||0),description:$('actionDescription').value.trim(),requiredDocuments:$('actionDocuments').value.split('\n').map(x=>x.trim()).filter(Boolean),availabilityStatus:$('actionAvailable').value,available:$('actionAvailable').value==='Available',order:Number($('actionOrder').value||0),updatedAt:serverTimestamp()};if(!data.serviceId||!data.name)return alert('Service aur Action Name required.');if(editAction)await updateDoc(doc(db,'serviceActions',editAction),data);else await addDoc(collection(db,'serviceActions'),{...data,createdAt:serverTimestamp()});clearA()});
$('serviceActionsList')?.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.ae){const x=actions.find(a=>a.id===b.dataset.ae);editAction=x.id;$('actionService').value=x.serviceId;$('actionName').value=x.name||'';$('actionCharge').value=x.serviceCharge||0;$('actionOfficialFee').value=x.officialFee||0;$('actionDescription').value=x.description||'';$('actionDocuments').value=(x.requiredDocuments||[]).join('\n');$('actionAvailable').value=x.availabilityStatus||((x.available!==false)?'Available':'Unavailable');$('actionOrder').value=x.order||1;$('saveServiceAction').textContent='Update Action';$('portalbuilderPage')?.scrollIntoView({behavior:'smooth',block:'start'})}else if(b.dataset.ad&&confirm('Action aur uske form fields delete karein?')){const aid=b.dataset.ad;const fs=await getDocs(collection(db,'formFields'));const batch=writeBatch(db);fs.docs.forEach(d=>{if(d.data().actionId===aid)batch.delete(d.ref)});batch.delete(doc(db,'serviceActions',aid));await batch.commit()}});
$('serviceChargesTable')?.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.chargeUpdate||b.dataset.chargeDelete;if(!id)return;const ref=doc(db,'serviceActions',id);if(b.dataset.chargeDelete){if(!confirm('Is action ka service charge ₹0 karna hai? Action delete nahi hoga.'))return;await updateDoc(ref,{serviceCharge:0,updatedAt:serverTimestamp()});return}const input=document.querySelector(`[data-charge-input="${id}"]`),status=document.querySelector(`[data-charge-status="${id}"]`);await updateDoc(ref,{serviceCharge:Number(input?.value||0),availabilityStatus:status?.value||'Available',available:(status?.value||'Available')==='Available',updatedAt:serverTimestamp()});alert('Service charge updated successfully.')});
$('chargeServiceFilter')?.addEventListener('change',renderCharges);$('chargeSearch')?.addEventListener('input',renderCharges);$('actionServiceFilter')?.addEventListener('change',renderActions);$('clearServiceAction')?.addEventListener('click',clearA);$('fieldAction')?.addEventListener('change',renderFields);
$('saveFormField')?.addEventListener('click',async()=>{const data={actionId:$('fieldAction').value,label:$('fieldLabel').value.trim(),type:$('fieldType').value,options:$('fieldOptions').value.split(',').map(x=>x.trim()).filter(Boolean),required:$('fieldRequired').value==='true',profileKey:$('fieldProfileKey')?.value||'',order:Number($('fieldOrder').value||0),updatedAt:serverTimestamp()};if(!data.actionId||!data.label)return alert('Action aur Field Label required.');if(editField)await updateDoc(doc(db,'formFields',editField),data);else await addDoc(collection(db,'formFields'),{...data,createdAt:serverTimestamp()});clearF()});
$('formFieldsList')?.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.fe){const x=fields.find(a=>a.id===b.dataset.fe);editField=x.id;$('fieldAction').value=x.actionId;$('fieldLabel').value=x.label||'';$('fieldType').value=x.type||'text';$('fieldOptions').value=(x.options||[]).join(', ');$('fieldRequired').value=String(x.required!==false);if($('fieldProfileKey'))$('fieldProfileKey').value=x.profileKey||'';$('fieldOrder').value=x.order||1}else if(b.dataset.fd&&confirm('Field delete karein?'))await deleteDoc(doc(db,'formFields',b.dataset.fd))});
$('azSearch')?.addEventListener('input',renderAtoZ);
$('serviceAtoZTable')?.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.azSe){const x=services.find(s=>s.id===b.dataset.azSe);if(!x)return;editServiceId=x.id;$('builderServiceName').value=x.name||'';$('builderServiceDescription').value=x.description||'';$('builderServiceCategory').value=x.category||'Government';$('builderServiceIcon').value=x.icon||'';$('builderServiceStatus').value=x.status||'Published';$('builderServiceAvailability').value=x.availabilityStatus||'Available';if($('builderServiceTarget'))$('builderServiceTarget').value=x.target||'_self';$('saveBuilderService').textContent='Update Service';$('portalbuilderPage')?.scrollIntoView({behavior:'smooth',block:'start'});return}if(b.dataset.azSd){await deleteBuilderService(b.dataset.azSd);return}if(b.dataset.azAe){const x=actions.find(a=>a.id===b.dataset.azAe);if(!x)return;editAction=x.id;$('actionService').value=x.serviceId;$('actionName').value=x.name||'';$('actionCharge').value=x.serviceCharge||0;$('actionOfficialFee').value=x.officialFee||0;$('actionDescription').value=x.description||'';$('actionDocuments').value=(x.requiredDocuments||[]).join('\n');$('actionAvailable').value=x.availabilityStatus||((x.available!==false)?'Available':'Unavailable');$('actionOrder').value=x.order||1;$('saveServiceAction').textContent='Update Action';$('portalbuilderPage')?.scrollIntoView({behavior:'smooth',block:'start'});return}const aid=b.dataset.azSave||b.dataset.azZero||b.dataset.azAd;if(!aid)return;if(b.dataset.azAd){if(!confirm('Action aur uske form fields permanently delete karein?'))return;const fsnap=await getDocs(collection(db,'formFields'));const batch=writeBatch(db);fsnap.docs.forEach(d=>{if(d.data().actionId===aid)batch.delete(d.ref)});batch.delete(doc(db,'serviceActions',aid));await batch.commit();return}const ref=doc(db,'serviceActions',aid);if(b.dataset.azZero){if(!confirm('Is action ka charge ₹0 karna hai?'))return;await updateDoc(ref,{serviceCharge:0,updatedAt:serverTimestamp()});return}const input=document.querySelector(`[data-az-charge="${aid}"]`),status=document.querySelector(`[data-az-status="${aid}"]`);await updateDoc(ref,{serviceCharge:Number(input?.value||0),availabilityStatus:status?.value||'Available',available:(status?.value||'Available')==='Available',updatedAt:serverTimestamp()});alert('Charge / availability updated.')}catch(err){alert(err.message)}});
$('existingFormSearch')?.addEventListener('input',renderExistingForms);
$('existingFormsList')?.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.formEdit){openExistingForm(b.dataset.formEdit);return}if(b.dataset.formDelete)await deleteExistingForm(b.dataset.formDelete)}catch(err){console.error(err);alert('Form operation failed: '+(err?.message||'Unknown error'))}});
$('clearFormField')?.addEventListener('click',clearF);init();



async function installMasterCatalog(options={}){
 const silent=options.silent===true,btn=$('installMasterCatalog'),msg=$('masterCatalogMessage');
 if(btn&&!silent){btn.disabled=true;btn.textContent='Installing...'}
 try{
  const existingServices=(await getDocs(collection(db,'services'))).docs.map(d=>({id:d.id,...d.data()}));
  const existingActions=(await getDocs(collection(db,'serviceActions'))).docs.map(d=>({id:d.id,...d.data()}));
  const existingFields=(await getDocs(collection(db,'formFields'))).docs.map(d=>({id:d.id,...d.data()}));
  const norm=v=>String(v||'').trim().toLowerCase().replace(/\s+/g,' ');
  const svcByName=new Map(existingServices.map(x=>[norm(x.name),x]));
  const actionByKey=new Map(existingActions.map(x=>[`${x.serviceId}|${norm(x.name)}`,x]));
  const fieldByKey=new Map(existingFields.map(x=>[`${x.actionId}|${norm(x.label)}`,x]));
  const writes=[];let addedServices=0,addedActions=0,addedFields=0;
  for(const svc of MASTER_SERVICES){
   let current=svcByName.get(norm(svc.name));
   const serviceDocId=current?.id||`svc_${svc.id}`;
   if(!current){writes.push(['set','services',serviceDocId,{name:svc.name,category:svc.category,icon:svc.icon,description:svc.description,status:'Published',availabilityStatus:'Available',featured:false,masterServiceId:svc.id,masterCatalogVersion:MASTER_CATALOG_VERSION,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}]);addedServices++;}else if(current.masterServiceId!==svc.id){writes.push(['set','services',serviceDocId,{masterServiceId:svc.id,masterCatalogVersion:MASTER_CATALOG_VERSION,updatedAt:serverTimestamp()}]);}
   for(let ai=0;ai<svc.actions.length;ai++){
    const a=svc.actions[ai],name=a[0],charge=Number(a[1]||0),availability=a[2]||'Available',docs=a[3]||[];
    let currentAction=actionByKey.get(`${serviceDocId}|${norm(name)}`);
    const aid=currentAction?.id||actionId(svc.id,name);
    if(!currentAction){writes.push(['set','serviceActions',aid,{serviceId:serviceDocId,name,serviceCharge:charge,officialFee:0,description:`${svc.name} - ${name} service/assistance request.`,requiredDocuments:docs,availabilityStatus:availability,available:availability==='Available',order:(ai+1)*10,masterServiceId:svc.id,masterCatalogVersion:MASTER_CATALOG_VERSION,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}]);addedActions++;}
    const fdefs=fieldsFor(a);
    for(let fi=0;fi<fdefs.length;fi++){
      const f=fdefs[fi];const key=`${aid}|${norm(f.label)}`;
      if(fieldByKey.has(key))continue;
      const fid=`fld_${aid}_${fi+1}`.slice(0,120);
      writes.push(['set','formFields',fid,{actionId:aid,...f,masterCatalogVersion:MASTER_CATALOG_VERSION,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}]);addedFields++;
    }
   }
  }
  for(let i=0;i<writes.length;i+=350){const batch=writeBatch(db);for(const [op,col,id,data] of writes.slice(i,i+350)){batch.set(doc(db,col,id),data,{merge:true})}await batch.commit()}
  await setDoc(doc(db,'settings','masterCatalog'),{version:MASTER_CATALOG_VERSION,installedAt:serverTimestamp(),serviceCount:MASTER_SERVICES.length,actionCount:MASTER_SERVICES.reduce((n,s)=>n+s.actions.length,0),installedComplete:true},{merge:true});
  if(msg&&!silent)msg.textContent=`✅ Master Catalogue ready: ${addedServices} new services, ${addedActions} new actions, ${addedFields} form fields added. Existing prices/actions preserved.`;
  if(!silent)alert('Complete master service catalogue installed / synced successfully.');
 }catch(e){console.error(e);if(msg&&!silent)msg.textContent='❌ '+e.message;if(!silent)alert('Master catalogue error: '+e.message)}finally{if(btn&&!silent){btn.disabled=false;btn.textContent='Install / Sync Complete Master Catalogue'}}
}
$('installMasterCatalog')?.addEventListener('click',()=>installMasterCatalog());
setTimeout(()=>installMasterCatalog({silent:true}),700);
