import {db} from './firebase-config.js';
import {collection,onSnapshot,doc,setDoc,increment,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const $=id=>document.getElementById(id);let settings={},services=[],updates=[],docs=[],images=[],videos=[];
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const digits=v=>String(v||'').replace(/\D/g,''); const wa=(name='CSC service')=>{let n=digits(settings.whatsappNumber||settings.contactNumber||'9637832490');if(n.length===10)n='91'+n;return `https://wa.me/${n}?text=${encodeURIComponent('Hello, I want to apply for '+name+'. Please send details and required documents.')}`};
const time=v=>v?.toDate?.().getTime?.()||v?.seconds*1000||new Date(v||0).getTime()||0;
function unique(arr,key='name'){const seen=new Set;return arr.filter(x=>{const k=String(x[key]||'').trim().toLocaleLowerCase();if(!k||seen.has(k))return false;seen.add(k);return true})}
function applySettings(){const name=settings.siteName||'Khobragade Computer Service Centre';document.querySelectorAll('[data-site-name]').forEach(e=>e.textContent=name);document.querySelectorAll('[data-tagline]').forEach(e=>e.textContent=settings.tagline||'CSC Digital Seva & Government Services');document.querySelectorAll('[data-address]').forEach(e=>e.textContent=settings.address||'Nagpur, Maharashtra, India');document.querySelectorAll('[data-phone]').forEach(e=>e.textContent=settings.contactNumber||'9637832490');document.querySelectorAll('a[data-call]').forEach(e=>e.href='tel:+'+(digits(settings.contactNumber||'9637832490').length===10?'91':'')+digits(settings.contactNumber||'9637832490'));document.querySelectorAll('a[data-wa]').forEach(e=>e.href=wa());const h=$('heroTitle');const sub=$('heroSubtitle');if(document.body.dataset.page==='home'){if(h)h.textContent=settings.heroTitle||h.dataset.default||name;if(sub)sub.textContent=settings.heroSubtitle||settings.tagline||sub.dataset.default||'';}const f=$('footerText');if(f)f.textContent=settings.footerText||'© 2026 All Rights Reserved';if(settings.youtubeChannel)document.querySelectorAll('[data-youtube]').forEach(e=>e.href=settings.youtubeChannel)}
function serviceCard(x){return `<article class="pro-card"><div class="card-icon">${esc(x.icon||'📄')}</div><span class="tag">${esc(x.category||'CSC Service')}</span><h3>${esc(x.name)}</h3><p>${esc(x.description||'Online application and assistance available.')}</p><div class="card-actions"><a class="btn btn-wa" target="_blank" rel="noopener" href="${wa(x.name)}">💬 Apply</a></div></article>`}
function renderServices(){const c=$('serviceGrid');if(!c)return;const q=($('serviceSearch')?.value||'').toLowerCase().trim();const filter=document.body.dataset.filter||'';let rows=unique(services).filter(x=>(x.status||'Published')==='Published');if(filter){const keys=filter.split(',').map(k=>k.trim()).filter(Boolean);rows=rows.filter(x=>{const text=`${x.category||''} ${x.name||''} ${x.description||''}`.toLowerCase();return keys.some(k=>text.includes(k))})}if(q)rows=rows.filter(x=>`${x.category||''} ${x.name||''} ${x.description||''}`.toLowerCase().includes(q));rows.sort((a,b)=>Number(!!b.featured)-Number(!!a.featured)||String(a.name).localeCompare(String(b.name)));const lim=Number(c.dataset.limit||0);if(lim)rows=rows.slice(0,lim);c.innerHTML=rows.length?rows.map(serviceCard).join(''):'<div class="empty">No matching published services. Admin Dashboard se service publish karte hi yahan automatically dikhegi.</div>';const count=$('serviceCount');if(count)count.textContent=unique(services).filter(x=>(x.status||'Published')==='Published').length+'+'}
function renderUpdates(){const c=$('updateGrid');if(!c)return;let rows=updates.filter(x=>(x.status||'Published')==='Published').sort((a,b)=>Number(!!b.featured)-Number(!!a.featured)||time(b.createdAt||b.updatedAt)-time(a.createdAt||a.updatedAt));const lim=Number(c.dataset.limit||0);if(lim)rows=rows.slice(0,lim);c.innerHTML=rows.length?rows.map(x=>`<article class="pro-card"><div class="card-icon">📢</div><span class="tag">${esc(x.category||'Government Update')}</span><h3>${esc(x.title)}</h3><p>${esc(x.description||'')}</p></article>`).join(''):'<div class="empty">No published updates yet.</div>'}
function renderDocs(){const c=$('documentGrid');if(!c)return;let rows=docs.filter(x=>(x.status||'Published')==='Published');c.innerHTML=rows.length?rows.map(x=>`<article class="pro-card"><div class="card-icon">📄</div><span class="tag">${esc(x.category||'Document')}</span><h3>${esc(x.title)}</h3><p>Official/useful document shared from Admin Dashboard.</p><div class="card-actions"><a class="btn btn-blue" target="_blank" rel="noopener" href="${esc(x.url||'#')}">Open Document</a></div></article>`).join(''):'<div class="empty">No public documents available.</div>'}
function renderMedia(){const c=$('mediaGrid');if(!c)return;const a=images.filter(x=>(x.status||'Published')==='Published').slice(0,4).map(x=>`<article class="pro-card media-card"><img loading="lazy" src="${esc(x.url||'')}" alt="${esc(x.title||'Gallery image')}"><span class="tag">${esc(x.category||'Gallery')}</span><h3>${esc(x.title||'Website Gallery')}</h3></article>`);const b=videos.filter(x=>(x.status||'Published')==='Published').slice(0,4).map(x=>`<article class="pro-card"><div class="card-icon">▶️</div><h3>${esc(x.title||'YouTube Video')}</h3><p>${esc(x.description||'')}</p><a class="btn btn-blue" target="_blank" rel="noopener" href="${esc(x.link||'#')}">Watch Video</a></article>`);c.innerHTML=[...a,...b].join('')||'<div class="empty">Gallery and videos will appear here when published from Admin.</div>'}
function renderBreaking(){const b=updates;const n=window.__notifications||[];const item=n.filter(x=>(x.status||'Published')==='Published'&&x.type==='breaking').sort((a,b)=>time(b.createdAt)-time(a.createdAt))[0];const bar=$('breakingBar');if(item&&bar){$('breakingText').textContent=`${item.title}${item.description?' — '+item.description:''}`;bar.style.display='block'}else if(bar)bar.style.display='none'}
onSnapshot(doc(db,'settings','website'),s=>{if(s.exists())settings=s.data();applySettings();renderServices()});onSnapshot(collection(db,'services'),s=>{services=s.docs.map(d=>({id:d.id,...d.data()}));renderServices()});onSnapshot(collection(db,'updates'),s=>{updates=s.docs.map(d=>({id:d.id,...d.data()}));renderUpdates()});onSnapshot(collection(db,'documents'),s=>{docs=s.docs.map(d=>({id:d.id,...d.data()}));renderDocs()});onSnapshot(collection(db,'images'),s=>{images=s.docs.map(d=>({id:d.id,...d.data()}));renderMedia()});onSnapshot(collection(db,'youtube'),s=>{videos=s.docs.map(d=>({id:d.id,...d.data()}));renderMedia()});onSnapshot(collection(db,'notifications'),s=>{window.__notifications=s.docs.map(d=>({id:d.id,...d.data()}));renderBreaking()});$('serviceSearch')?.addEventListener('input',renderServices);
if(!sessionStorage.getItem('khobragadeVisitorCounted')){sessionStorage.setItem('khobragadeVisitorCounted','yes');const today=new Date().toISOString().slice(0,10);Promise.all([setDoc(doc(db,'analytics','site'),{totalVisitors:increment(1),updatedAt:serverTimestamp()},{merge:true}),setDoc(doc(db,'visitorDaily',today),{date:today,count:increment(1),updatedAt:serverTimestamp()},{merge:true})]).catch(()=>{})}
