
import {db} from './firebase-config.js';
import {collection,onSnapshot,doc,setDoc,increment,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import {DEFAULT_SERVICES,DEFAULT_SCHEMES,DEFAULT_DIVYANG,DOCUMENT_CHECKLISTS} from './catalog-data.js';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const norm=v=>String(v||'').replace(/\s+/g,' ').trim().toLowerCase(), digits=v=>String(v||'').replace(/\D/g,'');
let settings={},services=[],updates=[],docs=[],notifications=[],pages={};
const time=v=>v?.toDate?.().getTime?.()||v?.seconds*1000||new Date(v||0).getTime()||0;
const wa=(name='Digital service')=>{let n=digits(settings.whatsappNumber||settings.contactNumber||'9637832490');if(n.length===10)n='91'+n;return `https://wa.me/${n}?text=${encodeURIComponent('Namaste, mujhe '+name+' ke liye jankari/apply assistance chahiye. Required documents aur process bataiye.')}`};
function mergeUnique(base,live){const m=new Map();base.forEach(x=>m.set(norm(x.name),{...x,status:'Published'}));live.forEach(x=>{let k=norm(x.name);if(!k)return;(x.status||'Published')==='Published'?m.set(k,x):m.delete(k)});return [...m.values()]}
function relevant(kind){if(kind==='yojana')return services.filter(x=>/yojana|scheme|scholarship|farmer|agriculture|pension|women|health|housing|employment|labour|food|maharashtra/i.test(`${x.category||''} ${x.name||''} ${x.description||''}`));if(kind==='divyang')return services.filter(x=>/divyang|udid|disability|handicap/i.test(`${x.category||''} ${x.name||''} ${x.description||''}`));return services}
function base(kind){return kind==='yojana'?DEFAULT_SCHEMES:kind==='divyang'?DEFAULT_DIVYANG:DEFAULT_SERVICES}
function applySettings(){let name=settings.siteName||'Khobragade Computer Service Centre';document.querySelectorAll('[data-site-name]').forEach(e=>e.textContent=name);document.querySelectorAll('[data-tagline]').forEach(e=>e.textContent=settings.tagline||'Digital Seva & Government Service Assistance');document.querySelectorAll('[data-address]').forEach(e=>e.textContent=settings.address||'Nagpur, Maharashtra, India');document.querySelectorAll('[data-phone]').forEach(e=>e.textContent=settings.contactNumber||'9637832490');document.querySelectorAll('[data-wa]').forEach(e=>e.href=wa(e.dataset.message||'Digital service'));document.querySelectorAll('[data-call]').forEach(e=>{let n=digits(settings.contactNumber||'9637832490');e.href='tel:'+(n.length===10?'+91':'')+n});document.querySelectorAll('[data-youtube]').forEach(e=>e.href=settings.youtubeChannel||'https://youtube.com/@niteshkhobragade8');if($('heroTitle'))$('heroTitle').textContent=settings.heroTitle||name;if($('heroSubtitle'))$('heroSubtitle').textContent=settings.heroSubtitle||'Online citizen services, government schemes and document assistance at one place.';if($('homeAboutTitle'))$('homeAboutTitle').textContent=settings.homeAboutTitle||name;if($('homeAboutText'))$('homeAboutText').textContent=settings.homeAboutText||'Digital applications, government schemes, citizen services and document guidance ke liye professional assistance.';if($('footerText'))$('footerText').textContent=settings.footerText||'© 2026 All Rights Reserved'}
function applyPage(){let key=document.body.dataset.page||document.body.dataset.catalog||'home',p=pages[key];if(!p||p.status==='Draft')return;if($('pageHeroTitle')&&p.title)$('pageHeroTitle').textContent=p.title;if($('pageHeroSubtitle')&&p.subtitle)$('pageHeroSubtitle').textContent=p.subtitle;if($('pageDescription')&&p.description)$('pageDescription').textContent=p.description}
function card(x){let id='item-'+norm(x.name).replace(/[^a-z0-9]+/g,'-');return `<article class="pro-card" id="${id}"><div class="card-icon">${esc(x.icon||'📄')}</div><span class="tag">${esc(x.category||'Digital Service')}</span><h3>${esc(x.name)}</h3><p>${esc(x.description||'Online application aur document guidance assistance available.')}</p><div class="card-actions"><a class="btn btn-wa" target="_blank" rel="noopener" href="${wa(x.name)}">WhatsApp Apply</a></div></article>`}
function renderServices(){let c=$('serviceGrid');if(!c)return;let kind=document.body.dataset.catalog||'services',q=norm($('serviceSearch')?.value||new URLSearchParams(location.search).get('q'));let rows=mergeUnique(base(kind),relevant(kind));if(q)rows=rows.filter(x=>norm(`${x.name} ${x.category} ${x.description}`).includes(q));rows.sort((a,b)=>Number(!!b.featured)-Number(!!a.featured)||String(a.name).localeCompare(String(b.name)));c.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">No matching result found.</div>'}
function renderFeatured(){let c=$('featuredServiceGrid');if(!c)return;let preferred=['eShram Card','PAN Card','Voter ID','ABHA Card','Ayushman Card','Maha ID','Income Certificate','UDID Card'];let all=mergeUnique(DEFAULT_SERVICES,services);let rows=preferred.map(n=>all.find(x=>norm(x.name).includes(norm(n)))).filter(Boolean);if(rows.length<8)rows=[...rows,...all.filter(x=>!rows.includes(x)).slice(0,8-rows.length)];c.innerHTML=rows.slice(0,8).map(x=>`<a class="pro-card service-link" href="services.html?q=${encodeURIComponent(x.name)}"><div class="card-icon">${esc(x.icon||'📄')}</div><span class="tag">${esc(x.category||'Service')}</span><h3>${esc(x.name)}</h3><p>${esc(x.description||'Digital service assistance')}</p><div class="arrow">View service →</div></a>`).join('')}
function renderDocs(){let c=$('documentGrid');if(!c)return;let q=norm($('documentSearchPublic')?.value||new URLSearchParams(location.search).get('q'));let a=DOCUMENT_CHECKLISTS.filter(x=>!q||norm(`${x.title} ${x.category} ${x.items.join(' ')}`).includes(q)).map(x=>`<article class="pro-card"><div class="card-icon">📋</div><span class="tag">${esc(x.category)}</span><h3>${esc(x.title)}</h3><ol>${x.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ol><div class="card-actions"><a class="btn btn-wa" target="_blank" href="${wa(x.title)}">WhatsApp Confirm</a></div></article>`);let b=docs.filter(x=>(x.status||'Published')==='Published'&&(!q||norm(`${x.title} ${x.category}`).includes(q))).map(x=>`<article class="pro-card"><div class="card-icon">📄</div><h3>${esc(x.title)}</h3>${x.url?`<a class="btn btn-blue" target="_blank" href="${esc(x.url)}">Open Document</a>`:''}</article>`);c.innerHTML=[...a,...b].join('')||'<div class="empty">No matching documents found.</div>'}
function renderNotice(){let n=notifications.filter(x=>(x.status||'Published')==='Published').sort((a,b)=>time(b.createdAt||b.updatedAt)-time(a.createdAt||a.updatedAt))[0],box=$('homeNotification'),bar=$('breakingBar');if(n&&box)box.innerHTML=`<strong>📢 ${esc(n.title)}</strong><p>${esc(n.description||'')}</p>`;let breaking=notifications.filter(x=>(x.status||'Published')==='Published'&&x.type==='breaking').sort((a,b)=>time(b.createdAt)-time(a.createdAt))[0];if(breaking&&bar){$('breakingText').textContent=breaking.title+(breaking.description?' — '+breaking.description:'');bar.style.display='block'}else if(bar)bar.style.display='none'}
function searchIndex(){let out=[];mergeUnique(DEFAULT_SERVICES,services).forEach(x=>out.push({name:x.name,meta:x.category||'Service',url:'services.html?q='+encodeURIComponent(x.name),text:`${x.name} ${x.category} ${x.description}`}));mergeUnique(DEFAULT_SCHEMES,relevant('yojana')).forEach(x=>out.push({name:x.name,meta:'Government Yojana',url:'maharashtra.html?q='+encodeURIComponent(x.name),text:`${x.name} ${x.category} ${x.description}`}));mergeUnique(DEFAULT_DIVYANG,relevant('divyang')).forEach(x=>out.push({name:x.name,meta:'Divyang',url:'divyang.html?q='+encodeURIComponent(x.name),text:`${x.name} ${x.category} ${x.description}`}));DOCUMENT_CHECKLISTS.forEach(x=>out.push({name:x.title+' Documents',meta:'Documents',url:'documents.html?q='+encodeURIComponent(x.title),text:`${x.title} ${x.category} ${x.items.join(' ')}`}));return out}
function globalSearch(){let q=norm($('globalSearch')?.value),box=$('globalSearchResults');if(!box)return;if(q.length<2){box.style.display='none';return}let rows=searchIndex().filter(x=>norm(x.text).includes(q)).slice(0,12);box.innerHTML=rows.length?rows.map(x=>`<a class="search-result" href="${x.url}"><strong>${esc(x.name)}</strong><small>${esc(x.meta)} · Open page →</small></a>`).join(''):'<div class="search-result"><strong>No matching result found</strong><small>Try another keyword.</small></div>';box.style.display='block'}
document.querySelectorAll('.nav-links a').forEach(a=>{if(a.getAttribute('href')===location.pathname.split('/').pop()||(!location.pathname.split('/').pop()&&a.getAttribute('href')==='index.html'))a.classList.add('active')});
$('globalSearch')?.addEventListener('input',globalSearch);document.querySelector('.global-search-box button')?.addEventListener('click',globalSearch);document.addEventListener('click',e=>{if(!e.target.closest('.global-search-inner')&&$('globalSearchResults'))$('globalSearchResults').style.display='none'});
$('serviceSearch')?.addEventListener('input',renderServices);$('documentSearchPublic')?.addEventListener('input',renderDocs);
applySettings();renderServices();renderFeatured();renderDocs();applyPage();
onSnapshot(doc(db,'settings','website'),s=>{settings=s.exists()?s.data():{};applySettings();renderServices();renderFeatured();renderDocs()});
onSnapshot(collection(db,'services'),s=>{services=s.docs.map(d=>({id:d.id,...d.data()}));renderServices();renderFeatured()});
onSnapshot(collection(db,'documents'),s=>{docs=s.docs.map(d=>({id:d.id,...d.data()}));renderDocs()});
onSnapshot(collection(db,'notifications'),s=>{notifications=s.docs.map(d=>({id:d.id,...d.data()}));renderNotice()});
onSnapshot(collection(db,'pageContent'),s=>{pages={};s.docs.forEach(d=>pages[d.id]=d.data());applyPage()});
if(!sessionStorage.getItem('khobragadeVisitorCounted')){sessionStorage.setItem('khobragadeVisitorCounted','yes');let today=new Date().toISOString().slice(0,10);Promise.all([setDoc(doc(db,'analytics','site'),{totalVisitors:increment(1),updatedAt:serverTimestamp()},{merge:true}),setDoc(doc(db,'visitorDaily',today),{date:today,count:increment(1),updatedAt:serverTimestamp()},{merge:true})]).catch(()=>{})}
