import {db} from './firebase-config.js';
import {collection,onSnapshot,doc,setDoc,increment,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
import {DEFAULT_SERVICES,DEFAULT_SCHEMES,DEFAULT_DIVYANG,DOCUMENT_CHECKLISTS} from './catalog-data.js';

const $=id=>document.getElementById(id);let settings={},services=[],updates=[],docs=[],images=[],videos=[];
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const digits=v=>String(v||'').replace(/\D/g,'');
const norm=v=>String(v||'').replace(/\s+/g,' ').trim().toLocaleLowerCase();
const wa=(name='CSC service')=>{let n=digits(settings.whatsappNumber||settings.contactNumber||'9637832490');if(n.length===10)n='91'+n;return `https://wa.me/${n}?text=${encodeURIComponent('Namaste, mujhe '+name+' ke liye apply karna hai. Required documents aur process bataiye.')}`};
const time=v=>v?.toDate?.().getTime?.()||v?.seconds*1000||new Date(v||0).getTime()||0;

function mergeUnique(base,live){const map=new Map();base.forEach(x=>map.set(norm(x.name),{...x,_default:true,status:'Published'}));live.forEach(x=>{const k=norm(x.name);if(!k)return;if((x.status||'Published')==='Published')map.set(k,x);else if(map.has(k))map.delete(k)});return [...map.values()].filter(x=>x.name)}
function applySettings(){const name=settings.siteName||'Khobragade Computer Service Centre';document.querySelectorAll('[data-site-name]').forEach(e=>e.textContent=name);document.querySelectorAll('[data-tagline]').forEach(e=>e.textContent=settings.tagline||'CSC Digital Seva & Government Services');document.querySelectorAll('[data-address]').forEach(e=>e.textContent=settings.address||'Nagpur, Maharashtra, India');document.querySelectorAll('[data-phone]').forEach(e=>e.textContent=settings.contactNumber||'9637832490');document.querySelectorAll('a[data-call]').forEach(e=>e.href='tel:+'+(digits(settings.contactNumber||'9637832490').length===10?'91':'')+digits(settings.contactNumber||'9637832490'));document.querySelectorAll('a[data-wa]').forEach(e=>e.href=wa(e.dataset.message||'CSC service'));const h=$('heroTitle');const sub=$('heroSubtitle');if(document.body.dataset.page==='home'){if(h)h.textContent=settings.heroTitle||h.dataset.default||name;if(sub)sub.textContent=settings.heroSubtitle||settings.tagline||sub.dataset.default||'';}const f=$('footerText');if(f)f.textContent=settings.footerText||'© 2026 All Rights Reserved';if(settings.youtubeChannel)document.querySelectorAll('[data-youtube]').forEach(e=>e.href=settings.youtubeChannel)}
function serviceCard(x){return `<article class="pro-card"><div class="card-icon">${esc(x.icon||'📄')}</div><span class="tag">${esc(x.category||'CSC Service')}</span><h3>${esc(x.name)}</h3><p>${esc(x.description||'Online application, documents aur process assistance available.')}</p><div class="card-actions"><a class="btn btn-wa" target="_blank" rel="noopener" href="${wa(x.name)}">💬 WhatsApp Apply</a></div></article>`}
function relevantLive(kind){if(kind==='yojana')return services.filter(x=>/yojana|scheme|scholarship|farmer|agriculture|pension|women|health|housing|employment|labour|food|maharashtra/i.test(`${x.category||''} ${x.name||''} ${x.description||''}`));if(kind==='divyang')return services.filter(x=>/divyang|udid|disability|handicap/i.test(`${x.category||''} ${x.name||''} ${x.description||''}`));return services}
function baseFor(kind){if(kind==='yojana')return DEFAULT_SCHEMES;if(kind==='divyang')return DEFAULT_DIVYANG;return DEFAULT_SERVICES}
function renderServices(){const c=$('serviceGrid');if(!c)return;const kind=document.body.dataset.catalog||'services';const q=($('serviceSearch')?.value||'').toLowerCase().trim();let rows=mergeUnique(baseFor(kind),relevantLive(kind));if(q)rows=rows.filter(x=>`${x.category||''} ${x.name||''} ${x.description||''}`.toLowerCase().includes(q));rows.sort((a,b)=>Number(!!b.featured)-Number(!!a.featured)||String(a.category||'').localeCompare(String(b.category||''))||String(a.name).localeCompare(String(b.name)));const lim=Number(c.dataset.limit||0);if(lim)rows=rows.slice(0,lim);c.innerHTML=rows.length?rows.map(serviceCard).join(''):'<div class="empty">No matching service found.</div>';const count=$('serviceCount');if(count)count.textContent=rows.length+'+'}
function renderUpdates(){const c=$('updateGrid');if(!c)return;let rows=updates.filter(x=>(x.status||'Published')==='Published').sort((a,b)=>Number(!!b.featured)-Number(!!a.featured)||time(b.createdAt||b.updatedAt)-time(a.createdAt||a.updatedAt));const lim=Number(c.dataset.limit||0);if(lim)rows=rows.slice(0,lim);c.innerHTML=rows.length?rows.map(x=>`<article class="pro-card"><div class="card-icon">📢</div><span class="tag">${esc(x.category||'Government Update')}</span><h3>${esc(x.title)}</h3><p>${esc(x.description||'')}</p></article>`).join(''):'<div class="empty">Admin Dashboard se latest update publish karte hi yahan dikhega.</div>'}
function checklistCard(x){return `<article class="pro-card document-check"><div class="card-icon">📋</div><span class="tag">${esc(x.category)}</span><h3>${esc(x.title)} – Required Documents</h3><ol>${x.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ol><div class="card-actions"><a class="btn btn-wa" target="_blank" rel="noopener" href="${wa(x.title)}">💬 Documents Confirm करें</a></div></article>`}
function renderDocs(){const c=$('documentGrid');if(!c)return;const q=($('documentSearchPublic')?.value||'').toLowerCase().trim();let checklists=DOCUMENT_CHECKLISTS.filter(x=>!q||`${x.title} ${x.category} ${x.items.join(' ')}`.toLowerCase().includes(q));let uploaded=docs.filter(x=>(x.status||'Published')==='Published').filter(x=>!q||`${x.title||''} ${x.category||''}`.toLowerCase().includes(q));const built=checklists.map(checklistCard);const live=uploaded.map(x=>`<article class="pro-card"><div class="card-icon">📄</div><span class="tag">${esc(x.category||'Document')}</span><h3>${esc(x.title)}</h3><p>Admin Dashboard se published official/useful document.</p>${x.url?`<div class="card-actions"><a class="btn btn-blue" target="_blank" rel="noopener" href="${esc(x.url)}">Open Document</a></div>`:''}</article>`);c.innerHTML=[...built,...live].join('')||'<div class="empty">No documents found.</div>'}
function renderMedia(){const c=$('mediaGrid');if(!c)return;const a=images.filter(x=>(x.status||'Published')==='Published').slice(0,4).map(x=>`<article class="pro-card media-card"><img loading="lazy" src="${esc(x.url||'')}" alt="${esc(x.title||'Gallery image')}"><span class="tag">${esc(x.category||'Gallery')}</span><h3>${esc(x.title||'Website Gallery')}</h3></article>`);const b=videos.filter(x=>(x.status||'Published')==='Published').slice(0,4).map(x=>`<article class="pro-card"><div class="card-icon">▶️</div><h3>${esc(x.title||'YouTube Video')}</h3><p>${esc(x.description||'')}</p><a class="btn btn-blue" target="_blank" rel="noopener" href="${esc(x.link||'#')}">Watch Video</a></article>`);c.innerHTML=[...a,...b].join('')||'<div class="empty">Gallery and videos Admin se publish karte hi yahan dikhenge.</div>'}
function renderBreaking(){const n=window.__notifications||[];const item=n.filter(x=>(x.status||'Published')==='Published'&&x.type==='breaking').sort((a,b)=>time(b.createdAt)-time(a.createdAt))[0];const bar=$('breakingBar');if(item&&bar){$('breakingText').textContent=`${item.title}${item.description?' — '+item.description:''}`;bar.style.display='block'}else if(bar)bar.style.display='none'}

applySettings();renderServices();renderDocs();

onSnapshot(doc(db,'settings','website'),s=>{if(s.exists())settings=s.data();applySettings();renderServices();renderDocs()});
onSnapshot(collection(db,'services'),s=>{services=s.docs.map(d=>({id:d.id,...d.data()}));renderServices()});
onSnapshot(collection(db,'updates'),s=>{updates=s.docs.map(d=>({id:d.id,...d.data()}));renderUpdates()});
onSnapshot(collection(db,'documents'),s=>{docs=s.docs.map(d=>({id:d.id,...d.data()}));renderDocs()});
onSnapshot(collection(db,'images'),s=>{images=s.docs.map(d=>({id:d.id,...d.data()}));renderMedia()});
onSnapshot(collection(db,'youtube'),s=>{videos=s.docs.map(d=>({id:d.id,...d.data()}));renderMedia()});
onSnapshot(collection(db,'notifications'),s=>{window.__notifications=s.docs.map(d=>({id:d.id,...d.data()}));renderBreaking()});
$('serviceSearch')?.addEventListener('input',renderServices);$('documentSearchPublic')?.addEventListener('input',renderDocs);
if(!sessionStorage.getItem('khobragadeVisitorCounted')){sessionStorage.setItem('khobragadeVisitorCounted','yes');const today=new Date().toISOString().slice(0,10);Promise.all([setDoc(doc(db,'analytics','site'),{totalVisitors:increment(1),updatedAt:serverTimestamp()},{merge:true}),setDoc(doc(db,'visitorDaily',today),{date:today,count:increment(1),updatedAt:serverTimestamp()},{merge:true})]).catch(()=>{})}
