import { db } from "./firebase-config.js";
import { doc, getDoc, setDoc, increment, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";

function pageKey(){const f=(location.pathname.split('/').pop()||'index.html').toLowerCase();return ({'index.html':'home','services.html':'services','maharashtra.html':'yojana','divyang.html':'divyang','documents.html':'documents','contact.html':'contact'})[f]||document.body.dataset.page||document.body.dataset.catalog||'home'}
function ensureMeta(name,property=false){let q=property?`meta[property="${name}"]`:`meta[name="${name}"]`;let e=document.head.querySelector(q);if(!e){e=document.createElement('meta');e.setAttribute(property?'property':'name',name);document.head.appendChild(e)}return e}
function ensureLink(rel){let e=document.head.querySelector(`link[rel="${rel}"]`);if(!e){e=document.createElement('link');e.rel=rel;document.head.appendChild(e)}return e}
async function applySeo(){try{const key=pageKey();const snap=await getDoc(doc(db,'seoSettings',key));if(!snap.exists())return;const x=snap.data();if(x.title)document.title=x.title;if(x.description)ensureMeta('description').content=x.description;if(x.keywords)ensureMeta('keywords').content=x.keywords;if(x.title){ensureMeta('og:title',true).content=x.title;ensureMeta('twitter:title').content=x.title}if(x.description){ensureMeta('og:description',true).content=x.description;ensureMeta('twitter:description').content=x.description}if(x.image){ensureMeta('og:image',true).content=x.image;ensureMeta('twitter:image').content=x.image;ensureMeta('twitter:card').content='summary_large_image'}const canonical=x.canonical||location.href.split('?')[0].split('#')[0];ensureLink('canonical').href=canonical;ensureMeta('og:url',true).content=canonical}catch(e){console.warn('SEO load error:',e)}}
function cleanId(v){return String(v||'general').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120)||'general'}
async function track(name,field){const id=cleanId(name);try{await setDoc(doc(db,'serviceAnalytics',id),{name:name||'General WhatsApp',[field]:increment(1),lastActivityAt:serverTimestamp()},{merge:true})}catch(e){console.warn('Analytics track error:',e)}}
function inferName(el){return el?.closest('.pro-card')?.querySelector('h3')?.textContent?.trim()||el?.dataset?.message||'General WhatsApp'}
document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;if(a.matches('.btn-wa,[data-wa]'))track(inferName(a),'whatsappClicks')});
const params=new URLSearchParams(location.search);const q=params.get('q');if(q&&['services','yojana','divyang'].includes(pageKey())){const k='service-view-'+pageKey()+'-'+cleanId(q);if(!sessionStorage.getItem(k)){sessionStorage.setItem(k,'1');track(q,'views')}}
applySeo();

/* V23: persistent English / Hindi / Marathi + Light / Dark on every public page */
const UI_LANG={
 hi:{'Home':'होम','Services':'सेवाएं','Yojana':'योजनाएं','Divyang':'दिव्यांग','Documents':'दस्तावेज','Contact':'संपर्क','YouTube':'यूट्यूब','WhatsApp':'व्हाट्सऐप','Search':'खोजें','All Services':'सभी सेवाएं','Government Yojana':'सरकारी योजनाएं','Divyang Services':'दिव्यांग सेवाएं','Quick Links':'त्वरित लिंक','Support':'सहायता','Contact Us':'संपर्क करें','View All Services':'सभी सेवाएं देखें','WhatsApp Enquiry':'व्हाट्सऐप पूछताछ','Latest Government Updates':'नवीनतम सरकारी अपडेट','Latest YouTube Videos':'नवीनतम यूट्यूब वीडियो','Popular Digital Services':'लोकप्रिय डिजिटल सेवाएं','Digital Service Centre':'डिजिटल सेवा केंद्र','Available':'उपलब्ध','Unavailable':'अनुपलब्ध','Coming Soon':'जल्द आ रहा है','Apply':'आवेदन करें','Required Documents':'आवश्यक दस्तावेज','Service Charge':'सेवा शुल्क','Open':'खोलें','Card':'कार्ड','Assistance':'सहायता','Registration':'पंजीकरण','Correction':'सुधार','Update':'अपडेट','Download':'डाउनलोड','Certificate':'प्रमाणपत्र','Pension':'पेंशन','Scholarship':'छात्रवृत्ति','Application':'आवेदन','New':'नया','Status':'स्थिति','Address':'पता','Photo':'फोटो','Signature':'हस्ताक्षर','Birth':'जन्म','Death':'मृत्यु','Income':'आय','Caste':'जाति','Domicile':'अधिवास','Ration':'राशन','Driving Licence':'ड्राइविंग लाइसेंस','Vehicle':'वाहन','Passport':'पासपोर्ट','Police Verification':'पुलिस सत्यापन','Banking':'बैंकिंग','Insurance':'बीमा','Agriculture':'कृषि','Labour':'श्रम','Employment':'रोजगार'},
 mr:{'Home':'होम','Services':'सेवा','Yojana':'योजना','Divyang':'दिव्यांग','Documents':'कागदपत्रे','Contact':'संपर्क','YouTube':'यूट्यूब','WhatsApp':'व्हॉट्सअॅप','Search':'शोधा','All Services':'सर्व सेवा','Government Yojana':'शासकीय योजना','Divyang Services':'दिव्यांग सेवा','Quick Links':'जलद दुवे','Support':'मदत','Contact Us':'संपर्क करा','View All Services':'सर्व सेवा पहा','WhatsApp Enquiry':'व्हॉट्सअॅप चौकशी','Latest Government Updates':'नवीनतम शासकीय अपडेट','Latest YouTube Videos':'नवीनतम यूट्यूब व्हिडिओ','Popular Digital Services':'लोकप्रिय डिजिटल सेवा','Digital Service Centre':'डिजिटल सेवा केंद्र','Available':'उपलब्ध','Unavailable':'अनुपलब्ध','Coming Soon':'लवकरच','Apply':'अर्ज करा','Required Documents':'आवश्यक कागदपत्रे','Service Charge':'सेवा शुल्क','Open':'उघडा','Card':'कार्ड','Assistance':'सहाय्य','Registration':'नोंदणी','Correction':'दुरुस्ती','Update':'अपडेट','Download':'डाउनलोड','Certificate':'प्रमाणपत्र','Pension':'पेन्शन','Scholarship':'शिष्यवृत्ती','Application':'अर्ज','New':'नवीन','Status':'स्थिती','Address':'पत्ता','Photo':'फोटो','Signature':'स्वाक्षरी','Birth':'जन्म','Death':'मृत्यू','Income':'उत्पन्न','Caste':'जात','Domicile':'अधिवास','Ration':'रेशन','Driving Licence':'ड्रायव्हिंग लायसन्स','Vehicle':'वाहन','Passport':'पासपोर्ट','Police Verification':'पोलीस पडताळणी','Banking':'बँकिंग','Insurance':'विमा','Agriculture':'कृषी','Labour':'कामगार','Employment':'रोजगार'}
};
const PUBLIC_ORIGINAL=new WeakMap();
function publicTranslate(lang){
 document.documentElement.lang=lang==='mr'?'mr':lang==='hi'?'hi':'en';
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 nodes.forEach(n=>{if(n.parentElement?.closest('script,style'))return;if(!PUBLIC_ORIGINAL.has(n))PUBLIC_ORIGINAL.set(n,n.nodeValue);const raw=PUBLIC_ORIGINAL.get(n),trim=String(raw||'').trim();if(!trim)return;if(lang==='en'){if(n.nodeValue!==raw)n.nodeValue=raw;return}let out=(UI_LANG[lang]||{})[trim]||trim;for(const[a,b]of Object.entries(UI_LANG[lang]||{})){if(out.includes(a))out=out.split(a).join(b)}const next=raw.replace(trim,out);if(n.nodeValue!==next)n.nodeValue=next});
 document.querySelectorAll('#langSelect').forEach(x=>x.value=lang);
}
function publicMode(mode){const dark=mode==='dark'||(mode==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.classList.toggle('dark',dark);document.querySelectorAll('#modeToggle').forEach(b=>b.textContent=dark?'☀️':'🌙')}
async function initPreferences(){
 let defaults={defaultLanguage:'en',defaultMode:'light'};try{const s=await getDoc(doc(db,'settings','website'));if(s.exists())defaults={...defaults,...s.data()}}catch(_){ }
 const lang=localStorage.getItem('kcscPublicLang')||defaults.defaultLanguage||'en',mode=localStorage.getItem('kcscPublicMode')||defaults.defaultMode||'light';publicTranslate(lang);publicMode(mode);
 document.querySelectorAll('#langSelect').forEach(sel=>sel.addEventListener('change',()=>{localStorage.setItem('kcscPublicLang',sel.value);publicTranslate(sel.value)}));
 document.querySelectorAll('#modeToggle').forEach(btn=>btn.addEventListener('click',()=>{const next=document.body.classList.contains('dark')?'light':'dark';localStorage.setItem('kcscPublicMode',next);publicMode(next)}));
 const ob=new MutationObserver(()=>{const l=localStorage.getItem('kcscPublicLang')||lang;if(l!=='en')publicTranslate(l)});ob.observe(document.body,{childList:true,subtree:true});
}
initPreferences();
