import { db } from "./supabase-app.js";
import { doc, getDoc, setDoc, increment, serverTimestamp } from "./supabase-compat.js";

function pageKey(){const f=(location.pathname.split('/').pop()||'index.html').toLowerCase();return ({'index.html':'home','services.html':'services','maharashtra.html':'yojana','divyang.html':'divyang','documents.html':'documents','contact.html':'contact'})[f]||document.body.dataset.page||document.body.dataset.catalog||'home'}
function ensureMeta(name,property=false){let q=property?`meta[property="${name}"]`:`meta[name="${name}"]`;let e=document.head.querySelector(q);if(!e){e=document.createElement('meta');e.setAttribute(property?'property':'name',name);document.head.appendChild(e)}return e}
function ensureLink(rel){let e=document.head.querySelector(`link[rel="${rel}"]`);if(!e){e=document.createElement('link');e.rel=rel;document.head.appendChild(e)}return e}
async function applySeo(){try{const key=pageKey();const snap=await getDoc(doc(db,'seoSettings',key));if(!snap.exists())return;const x=snap.data();if(x.title)document.title=x.title;if(x.description)ensureMeta('description').content=x.description;if(x.keywords)ensureMeta('keywords').content=x.keywords;if(x.title){ensureMeta('og:title',true).content=x.title;ensureMeta('twitter:title').content=x.title}if(x.description){ensureMeta('og:description',true).content=x.description;ensureMeta('twitter:description').content=x.description}if(x.image){ensureMeta('og:image',true).content=x.image;ensureMeta('twitter:image').content=x.image;ensureMeta('twitter:card').content='summary_large_image'}const canonical=x.canonical||location.href.split('?')[0].split('#')[0];ensureLink('canonical').href=canonical;ensureMeta('og:url',true).content=canonical}catch(e){console.warn('SEO load error:',e)}}
function cleanId(v){return String(v||'general').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120)||'general'}
async function track(name,field){const id=cleanId(name);try{await setDoc(doc(db,'serviceAnalytics',id),{name:name||'General WhatsApp',[field]:increment(1),lastActivityAt:serverTimestamp()},{merge:true})}catch(e){console.warn('Analytics track error:',e)}}
function inferName(el){return el?.closest('.pro-card')?.querySelector('h3')?.textContent?.trim()||el?.dataset?.message||'General WhatsApp'}
document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;if(a.matches('.btn-wa,[data-wa]'))track(inferName(a),'whatsappClicks')});
const params=new URLSearchParams(location.search);const q=params.get('q');if(q&&['services','yojana','divyang'].includes(pageKey())){const k='service-view-'+pageKey()+'-'+cleanId(q);if(!sessionStorage.getItem(k)){sessionStorage.setItem(k,'1');track(q,'views')}}
applySeo();
