import {moveToTrash} from './trash.js';
import {db} from './firebase-config.js';
import {collection,addDoc,doc,setDoc,updateDoc,onSnapshot,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');let rows=[],editId=null;
const DEF={name:'Pink Blue Professional',primary:'#ec4899',secondary:'#2563eb',accent:'#f59e0b',pageBg:'#f8fafc',surface:'#ffffff',text:'#132238',menuBg:'#172554',menuText:'#ffffff',menuActive:'#ec4899',footer:'#07182d',buttonText:'#ffffff',border:'#e2e8f0',radius:'20',mode:'light'};
function set(id,v){if($(id))$(id).value=v??''}function msg(t,c='info'){let e=$('themeManagerMessage');if(e){e.textContent=t;e.className='settings-message '+c}}function data(){return{name:$('themeName').value.trim()||'Untitled Theme',primary:$('themePrimary2').value,secondary:$('themeSecondary2').value,accent:$('themeAccent2').value,pageBg:$('themePageBg').value,surface:$('themeSurface').value,text:$('themeText').value,menuBg:$('themeMenuBg').value,menuText:$('themeMenuText').value,menuActive:$('themeMenuActive').value,footer:$('themeFooter').value,buttonText:$('themeButtonText').value,border:$('themeBorder').value,radius:$('themeRadius').value,mode:$('themeMode').value}}
function fill(x=DEF){for(const [i,k] of Object.entries({themeName:'name',themePrimary2:'primary',themeSecondary2:'secondary',themeAccent2:'accent',themePageBg:'pageBg',themeSurface:'surface',themeText:'text',themeMenuBg:'menuBg',themeMenuText:'menuText',themeMenuActive:'menuActive',themeFooter:'footer',themeButtonText:'buttonText',themeBorder:'border',themeRadius:'radius',themeMode:'mode'}))set(i,x[k]??DEF[k])}
async function apply(x){await setDoc(doc(db,'settings','activeTheme'),{...x,updatedAt:serverTimestamp()},{merge:false});await setDoc(doc(db,'settings','website'),{themePrimary:x.primary,themeSecondary:x.secondary,menuColor:x.menuBg,cardRadius:String(x.radius),defaultMode:x.mode,updatedAt:serverTimestamp()},{merge:true});msg('Theme applied to public website.','success')}
async function save(){let d=data();if(rows.some(x=>String(x.name).toLowerCase()===d.name.toLowerCase()))return msg('Theme name already exists.','error');await addDoc(collection(db,'themes'),{...d,createdAt:serverTimestamp()});await apply(d);msg('New theme saved and applied.','success')}
async function update(){if(!editId)return msg('Pehle saved theme ka Edit dabao.','error');let d=data();await updateDoc(doc(db,'themes',editId),{...d,updatedAt:serverTimestamp()});await apply(d);msg('Theme updated and applied.','success')}
function edit(id){let x=rows.find(v=>v.id===id);if(!x)return;editId=id;fill(x);msg('Editing: '+x.name,'info')}async function remove(id){let x=rows.find(v=>v.id===id);if(!x||!confirm(`Move theme "${x.name}" to Recycle Bin?`))return;await moveToTrash('themes',id,x);if(editId===id){editId=null;fill(DEF)}}async function reset(){fill(DEF);editId=null;await apply(DEF);msg('Pink + Blue default restored.','success')}
function render(){let b=$('themePresetList');if(!b)return,q=String($('themeSearch')?.value||'').toLowerCase(),a=rows.filter(x=>!q||String(x.name||'').toLowerCase().includes(q));b.innerHTML=a.length?a.map(x=>`<article class="content-card"><div style="display:flex;gap:8px;margin-bottom:10px"><span style="width:28px;height:28px;border-radius:50%;background:${esc(x.primary)}"></span><span style="width:28px;height:28px;border-radius:50%;background:${esc(x.secondary)}"></span><span style="width:28px;height:28px;border-radius:50%;background:${esc(x.menuBg)}"></span></div><h3>${esc(x.name)}</h3><small>${esc(x.mode||'light')} · Radius ${esc(x.radius||20)}px</small><div class="card-actions"><button class="action-btn edit" data-e="${x.id}">✏ Edit</button><button class="action-btn copy" data-a="${x.id}">✅ Apply</button><button class="action-btn delete" data-d="${x.id}">🗑 Delete</button></div></article>`).join(''):'<div class="empty-state">No saved themes. Pink + Blue default is available.</div>'}
$('saveThemePreset')?.addEventListener('click',()=>save().catch(e=>msg(e.message,'error')));$('updateThemePreset')?.addEventListener('click',()=>update().catch(e=>msg(e.message,'error')));$('applyThemePreview')?.addEventListener('click',()=>apply(data()).catch(e=>msg(e.message,'error')));$('resetDefaultTheme')?.addEventListener('click',()=>reset().catch(e=>msg(e.message,'error')));$('themeSearch')?.addEventListener('input',render);$('themePresetList')?.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.e)edit(b.dataset.e);if(b.dataset.a){let x=rows.find(v=>v.id===b.dataset.a);if(x)apply(x).catch(er=>msg(er.message,'error'))}if(b.dataset.d)remove(b.dataset.d).catch(er=>msg(er.message,'error'))});onSnapshot(collection(db,'themes'),s=>{rows=s.docs.map(d=>({id:d.id,...d.data()}));render()});window.addEventListener('DOMContentLoaded',()=>fill(DEF));